<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Kanvas\Locations\Models\Cities;
use Kanvas\Locations\Models\Countries;
use Kanvas\Locations\Models\States;

class CanadaCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        try {
            // Get Canada country
            $canada = Countries::where('code', 'CA')->firstOrFail();

            // Process cities data
            foreach ($this->getCitiesData() as $cityData) {
                // Find or create state
                $state = States::firstOrCreate(
                    [
                        'name' => $cityData['state'],
                        'countries_id' => $canada->id,
                    ],
                    [
                        'code' => $this->getProvinceCode($cityData['state']),
                    ]
                );

                // Create city
                Cities::firstOrCreate(
                    [
                        'name' => $cityData['name'],
                        'states_id' => $state->id,
                        'countries_id' => $canada->id,
                    ],
                    [
                        'latitude' => $cityData['latitude'],
                        'longitude' => $cityData['longitude'],
                    ]
                );
            }
        } catch (\Exception $e) {
            $this->command->error('Error seeding Canadian cities: ' . $e->getMessage());
        }

        Schema::enableForeignKeyConstraints();
    }

    /**
     * Get the province code for a given province name.
     */
    private function getProvinceCode(string $provinceName): string
    {
        $provinces = [
            'Alberta' => 'AB',
            'British Columbia' => 'BC',
            'Manitoba' => 'MB',
            'New Brunswick / Nouveau-Brunswick' => 'NB',
            'Newfoundland and Labrador' => 'NL',
            'Nova Scotia' => 'NS',
            'Ontario' => 'ON',
            'Prince Edward Island' => 'PE',
            'Québec' => 'QC',
            'Saskatchewan' => 'SK',
            'Northwest Territories' => 'NT',
            'Nunavut' => 'NU',
            'Yukon' => 'YT',
        ];

        return $provinces[$provinceName] ?? '';
    }

    /**
     * Get the cities data array.
     */
    private function getCitiesData(): array
    {
        return [
            0 => [
                'name' => 'North Vancouver',
                'state' => 'British Columbia',
                'latitude' => 49.3206294,
                'longitude' => -123.0737925,
            ],
            1 => [
                'name' => 'West Kelowna',
                'state' => 'British Columbia',
                'latitude' => 49.8585784,
                'longitude' => -119.582876,
            ],
            2 => [
                'name' => 'Edmonton',
                'state' => 'Alberta',
                'latitude' => 53.5462055,
                'longitude' => -113.491241,
            ],
            3 => [
                'name' => 'Regina',
                'state' => 'Saskatchewan',
                'latitude' => 50.44876,
                'longitude' => -104.61731,
            ],
            4 => [
                'name' => 'Prince Albert',
                'state' => 'Saskatchewan',
                'latitude' => 53.201097,
                'longitude' => -105.748901,
            ],
            5 => [
                'name' => 'Winkler',
                'state' => 'Manitoba',
                'latitude' => 49.187089,
                'longitude' => -97.937622,
            ],
            6 => [
                'name' => 'Morden',
                'state' => 'Manitoba',
                'latitude' => 49.1927055,
                'longitude' => -98.1014567,
            ],
            7 => [
                'name' => 'Southport',
                'state' => 'Manitoba',
                'latitude' => 49.91933905,
                'longitude' => -98.27576233119458,
            ],
            8 => [
                'name' => 'Morris',
                'state' => 'Manitoba',
                'latitude' => 49.34822025,
                'longitude' => -97.37227454180177,
            ],
            9 => [
                'name' => 'Selkirk',
                'state' => 'Manitoba',
                'latitude' => 50.146986,
                'longitude' => -96.880188,
            ],
            10 => [
                'name' => 'Steinbach',
                'state' => 'Manitoba',
                'latitude' => 49.530557,
                'longitude' => -96.69342,
            ],
            11 => [
                'name' => 'Kenora',
                'state' => 'Ontario',
                'latitude' => 49.766215,
                'longitude' => -94.4893528,
            ],
            12 => [
                'name' => 'Dauphin',
                'state' => 'Manitoba',
                'latitude' => 51.153509,
                'longitude' => -100.04425,
            ],
            13 => [
                'name' => 'Dryden',
                'state' => 'Ontario',
                'latitude' => 49.785698,
                'longitude' => -92.835846,
            ],
            14 => [
                'name' => 'Thompson',
                'state' => 'Manitoba',
                'latitude' => 55.743347,
                'longitude' => -97.863464,
            ],
            15 => [
                'name' => 'Fort McMurray',
                'state' => 'Alberta',
                'latitude' => 56.7291997,
                'longitude' => -111.3885221,
            ],
            16 => [
                'name' => 'Churchill',
                'state' => 'Manitoba',
                'latitude' => 58.7693101,
                'longitude' => -94.1736843,
            ],
            17 => [
                'name' => 'Sarnia',
                'state' => 'Ontario',
                'latitude' => 42.9743821,
                'longitude' => -82.403533,
            ],
            18 => [
                'name' => 'St. Thomas',
                'state' => 'Ontario',
                'latitude' => 42.779022,
                'longitude' => -81.1929882,
            ],
            19 => [
                'name' => 'Woodstock',
                'state' => 'Ontario',
                'latitude' => 43.1301111,
                'longitude' => -80.7562977,
            ],
            20 => [
                'name' => 'Stratford',
                'state' => 'Ontario',
                'latitude' => 43.3700899,
                'longitude' => -80.9818016,
            ],
            21 => [
                'name' => 'Brantford',
                'state' => 'Ontario',
                'latitude' => 43.1408157,
                'longitude' => -80.2631733,
            ],
            22 => [
                'name' => 'Waterloo',
                'state' => 'Ontario',
                'latitude' => 43.4652699,
                'longitude' => -80.5222961,
            ],
            23 => [
                'name' => 'Cambridge',
                'state' => 'Ontario',
                'latitude' => 43.3600536,
                'longitude' => -80.3123023,
            ],
            24 => [
                'name' => 'Guelph',
                'state' => 'Ontario',
                'latitude' => 43.5460516,
                'longitude' => -80.2493276,
            ],
            25 => [
                'name' => 'Kitchener',
                'state' => 'Ontario',
                'latitude' => 43.451291,
                'longitude' => -80.4927815,
            ],
            26 => [
                'name' => 'Hamilton',
                'state' => 'Ontario',
                'latitude' => 43.2560802,
                'longitude' => -79.8728583,
            ],
            27 => [
                'name' => 'Burlington',
                'state' => 'Ontario',
                'latitude' => 43.3248924,
                'longitude' => -79.7966835,
            ],
            28 => [
                'name' => 'Thorold',
                'state' => 'Ontario',
                'latitude' => 43.1249127,
                'longitude' => -79.2005935,
            ],
            29 => [
                'name' => 'Oakville',
                'state' => 'Ontario',
                'latitude' => 43.447436,
                'longitude' => -79.666672,
            ],
            30 => [
                'name' => 'Welland',
                'state' => 'Ontario',
                'latitude' => 42.9922181,
                'longitude' => -79.2484192,
            ],
            31 => [
                'name' => 'Niagara Falls',
                'state' => 'Ontario',
                'latitude' => 43.1065603,
                'longitude' => -79.0639039,
            ],
            32 => [
                'name' => 'St. Catharines',
                'state' => 'Ontario',
                'latitude' => 43.1579812,
                'longitude' => -79.2441003,
            ],
            33 => [
                'name' => 'Owen Sound',
                'state' => 'Ontario',
                'latitude' => 44.5678105,
                'longitude' => -80.9430094,
            ],
            34 => [
                'name' => 'Brampton',
                'state' => 'Ontario',
                'latitude' => 43.685832,
                'longitude' => -79.7599366,
            ],
            35 => [
                'name' => 'Mississauga',
                'state' => 'Ontario',
                'latitude' => 43.5896231,
                'longitude' => -79.6443879,
            ],
            36 => [
                'name' => 'Vaughan',
                'state' => 'Ontario',
                'latitude' => 43.7941544,
                'longitude' => -79.5268023,
            ],
            37 => [
                'name' => 'Newmarket',
                'state' => 'Ontario',
                'latitude' => 44.056258,
                'longitude' => -79.461708,
            ],
            38 => [
                'name' => 'Pickering',
                'state' => 'Ontario',
                'latitude' => 43.835765,
                'longitude' => -79.090576,
            ],
            39 => [
                'name' => 'Markham',
                'state' => 'Ontario',
                'latitude' => 43.8563707,
                'longitude' => -79.3376825,
            ],
            40 => [
                'name' => 'Toronto',
                'state' => 'Ontario',
                'latitude' => 43.6534817,
                'longitude' => -79.3839347,
            ],
            41 => [
                'name' => 'Richmond Hill',
                'state' => 'Ontario',
                'latitude' => 43.8801166,
                'longitude' => -79.4392925,
            ],
            42 => [
                'name' => 'Ajax',
                'state' => 'Ontario',
                'latitude' => 43.8505287,
                'longitude' => -79.0208814,
            ],
            43 => [
                'name' => 'Whitby',
                'state' => 'Ontario',
                'latitude' => 43.87982,
                'longitude' => -78.9421751,
            ],
            44 => [
                'name' => 'Oshawa',
                'state' => 'Ontario',
                'latitude' => 43.8975558,
                'longitude' => -78.8635324,
            ],
            45 => [
                'name' => 'Barrie',
                'state' => 'Ontario',
                'latitude' => 44.3893113,
                'longitude' => -79.6901736,
            ],
            46 => [
                'name' => 'Kawartha Lakes',
                'state' => 'Ontario',
                'latitude' => 44.3596825,
                'longitude' => -78.7421729,
            ],
            47 => [
                'name' => 'Quinte West',
                'state' => 'Ontario',
                'latitude' => 44.0988246,
                'longitude' => -77.5748551,
            ],
            48 => [
                'name' => 'Peterborough',
                'state' => 'Ontario',
                'latitude' => 44.3048009,
                'longitude' => -78.3199496,
            ],
            49 => [
                'name' => 'Thunder Bay',
                'state' => 'Ontario',
                'latitude' => 48.406414,
                'longitude' => -89.259796,
            ],
            50 => [
                'name' => 'Sault Ste. Marie',
                'state' => 'Ontario',
                'latitude' => 46.52391,
                'longitude' => -84.320068,
            ],
            51 => [
                'name' => 'Mastone',
                'state' => 'Ontario',
                'latitude' => 49.20269975,
                'longitude' => -89.886458555606,
            ],
            52 => [
                'name' => 'Elliot Lake',
                'state' => 'Ontario',
                'latitude' => 46.373464,
                'longitude' => -82.652893,
            ],
            53 => [
                'name' => 'North Bay',
                'state' => 'Ontario',
                'latitude' => 46.3092115,
                'longitude' => -79.4607617,
            ],
            54 => [
                'name' => 'Temiskaming Shores',
                'state' => 'Ontario',
                'latitude' => 47.512563,
                'longitude' => -79.675598,
            ],
            55 => [
                'name' => 'Kapuskasing',
                'state' => 'Ontario',
                'latitude' => 49.4160422,
                'longitude' => -82.43045240600158,
            ],
            56 => [
                'name' => 'Timmins',
                'state' => 'Ontario',
                'latitude' => 48.477473,
                'longitude' => -81.330414,
            ],
            57 => [
                'name' => 'Greater Sudbury',
                'state' => 'Ontario',
                'latitude' => 46.49272,
                'longitude' => -80.991211,
            ],
            58 => [
                'name' => 'Gatineau',
                'state' => 'Québec',
                'latitude' => 45.4277659,
                'longitude' => -75.710976,
            ],
            59 => [
                'name' => '(Old) Ottawa',
                'state' => 'Ontario',
                'latitude' => 45.394565549999996,
                'longitude' => -75.68233411939545,
            ],
            60 => [
                'name' => 'Mirabel',
                'state' => 'Québec',
                'latitude' => 45.6452452,
                'longitude' => -74.0731738,
            ],
            61 => [
                'name' => 'Saint-Jean-sur-Richelieu',
                'state' => 'Québec',
                'latitude' => 45.3056879,
                'longitude' => -73.2533401,
            ],
            62 => [
                'name' => 'Longueuil',
                'state' => 'Québec',
                'latitude' => 45.521906,
                'longitude' => -73.4644578,
            ],
            63 => [
                'name' => 'Laval',
                'state' => 'Québec',
                'latitude' => 45.60558895,
                'longitude' => -73.73441730569056,
            ],
            64 => [
                'name' => 'Montréal',
                'state' => 'Québec',
                'latitude' => 45.5031824,
                'longitude' => -73.5698065,
            ],
            65 => [
                'name' => 'Val-d\'Or',
                'state' => 'Québec',
                'latitude' => 48.1023356,
                'longitude' => -77.7875715,
            ],
            66 => [
                'name' => 'Trois-Rivières',
                'state' => 'Québec',
                'latitude' => 46.3432325,
                'longitude' => -72.5428485,
            ],
            67 => [
                'name' => 'Shawinigan',
                'state' => 'Québec',
                'latitude' => 46.5396581,
                'longitude' => -72.7518637,
            ],
            68 => [
                'name' => 'Saguenay',
                'state' => 'Québec',
                'latitude' => 48.405959,
                'longitude' => -71.069183,
            ],
            69 => [
                'name' => 'Moncton',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 46.097995,
                'longitude' => -64.80011,
            ],
            70 => [
                'name' => 'Dieppe',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 46.0945258,
                'longitude' => -64.7354772,
            ],
            71 => [
                'name' => 'Corner Brook',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 48.95317,
                'longitude' => -57.947388,
            ],
            72 => [
                'name' => 'Boat Harbour',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 47.4312796,
                'longitude' => -54.8535145,
            ],
            73 => [
                'name' => 'Mount Pearl',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 47.518910500000004,
                'longitude' => -52.814475267278404,
            ],
            74 => [
                'name' => 'St. John\'s',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 47.5614705,
                'longitude' => -52.7126162,
            ],
            75 => [
                'name' => 'YE KYI ရေကြည်',
                'state' => 'Québec',
                'latitude' => 48.3608359,
                'longitude' => -67.9334353,
            ],
            76 => [
                'name' => 'Whitehorse',
                'state' => 'Yukon',
                'latitude' => 60.721571,
                'longitude' => -135.054932,
            ],
            77 => [
                'name' => 'Nanaimo',
                'state' => 'British Columbia',
                'latitude' => 49.163877,
                'longitude' => -123.938122,
            ],
            78 => [
                'name' => 'Campbell River',
                'state' => 'British Columbia',
                'latitude' => 50.023071,
                'longitude' => -125.244153,
            ],
            79 => [
                'name' => 'Port Alberni',
                'state' => 'British Columbia',
                'latitude' => 49.2343668,
                'longitude' => -124.8056517,
            ],
            80 => [
                'name' => 'Courtenay',
                'state' => 'British Columbia',
                'latitude' => 49.6894061,
                'longitude' => -124.9954959,
            ],
            81 => [
                'name' => 'Powell River',
                'state' => 'British Columbia',
                'latitude' => 49.835676,
                'longitude' => -124.524412,
            ],
            82 => [
                'name' => 'Parksville',
                'state' => 'British Columbia',
                'latitude' => 49.3179514,
                'longitude' => -124.3117397,
            ],
            83 => [
                'name' => 'Prince Rupert',
                'state' => 'British Columbia',
                'latitude' => 54.3126572,
                'longitude' => -130.32549,
            ],
            84 => [
                'name' => 'Kitimat',
                'state' => 'British Columbia',
                'latitude' => 54.0535577,
                'longitude' => -128.6540519,
            ],
            85 => [
                'name' => 'Terrace',
                'state' => 'British Columbia',
                'latitude' => 54.5172715,
                'longitude' => -128.599548,
            ],
            86 => [
                'name' => 'Langford',
                'state' => 'British Columbia',
                'latitude' => 48.4497693,
                'longitude' => -123.5046662,
            ],
            87 => [
                'name' => 'Victoria',
                'state' => 'British Columbia',
                'latitude' => 48.4283182,
                'longitude' => -123.3649533,
            ],
            88 => [
                'name' => 'Richmond',
                'state' => 'British Columbia',
                'latitude' => 49.163168,
                'longitude' => -123.137414,
            ],
            89 => [
                'name' => 'Delta',
                'state' => 'British Columbia',
                'latitude' => 49.0846258,
                'longitude' => -123.057938,
            ],
            90 => [
                'name' => 'White Rock',
                'state' => 'British Columbia',
                'latitude' => 49.0235357,
                'longitude' => -122.797924,
            ],
            91 => [
                'name' => 'New Westminster',
                'state' => 'British Columbia',
                'latitude' => 49.2067726,
                'longitude' => -122.9108818,
            ],
            92 => [
                'name' => 'Surrey',
                'state' => 'British Columbia',
                'latitude' => 49.1913033,
                'longitude' => -122.849143,
            ],
            93 => [
                'name' => 'Langley City',
                'state' => 'British Columbia',
                'latitude' => 49.1039289,
                'longitude' => -122.657047,
            ],
            94 => [
                'name' => 'Abbotsford',
                'state' => 'British Columbia',
                'latitude' => 49.0521162,
                'longitude' => -122.329479,
            ],
            95 => [
                'name' => 'Chilliwack',
                'state' => 'British Columbia',
                'latitude' => 49.157677,
                'longitude' => -121.95143,
            ],
            96 => [
                'name' => 'West Vancouver',
                'state' => 'British Columbia',
                'latitude' => 49.3311208,
                'longitude' => -123.159479,
            ],
            97 => [
                'name' => 'Vancouver',
                'state' => 'British Columbia',
                'latitude' => 49.2608724,
                'longitude' => -123.113952,
            ],
            98 => [
                'name' => 'North Vancouver',
                'state' => 'British Columbia',
                'latitude' => 49.3206294,
                'longitude' => -123.0737925,
            ],
            99 => [
                'name' => 'Burnaby',
                'state' => 'British Columbia',
                'latitude' => 49.2433804,
                'longitude' => -122.972545,
            ],
            100 => [
                'name' => 'Squamish',
                'state' => 'British Columbia',
                'latitude' => 49.6980743,
                'longitude' => -123.1558612,
            ],
            101 => [
                'name' => 'Port Coquitlam',
                'state' => 'British Columbia',
                'latitude' => 49.2621643,
                'longitude' => -122.780542,
            ],
            102 => [
                'name' => 'Port Moody',
                'state' => 'British Columbia',
                'latitude' => 49.2822243,
                'longitude' => -122.829342,
            ],
            103 => [
                'name' => 'Coquitlam',
                'state' => 'British Columbia',
                'latitude' => 49.2842958,
                'longitude' => -122.793281,
            ],
            104 => [
                'name' => 'Maple Ridge',
                'state' => 'British Columbia',
                'latitude' => 49.2197345,
                'longitude' => -122.599707,
            ],
            105 => [
                'name' => 'Penticton',
                'state' => 'British Columbia',
                'latitude' => 49.5003268,
                'longitude' => -119.593249,
            ],
            106 => [
                'name' => 'West Kelowna',
                'state' => 'British Columbia',
                'latitude' => 49.8585784,
                'longitude' => -119.582876,
            ],
            107 => [
                'name' => 'Merritt',
                'state' => 'British Columbia',
                'latitude' => 50.1124876,
                'longitude' => -120.7884149,
            ],
            108 => [
                'name' => 'Kelowna',
                'state' => 'British Columbia',
                'latitude' => 49.8879177,
                'longitude' => -119.495902,
            ],
            109 => [
                'name' => 'Vernon',
                'state' => 'British Columbia',
                'latitude' => 50.2668671,
                'longitude' => -119.2718157,
            ],
            110 => [
                'name' => 'Trail',
                'state' => 'British Columbia',
                'latitude' => 49.0945296,
                'longitude' => -117.7097659,
            ],
            111 => [
                'name' => 'Castlegar',
                'state' => 'British Columbia',
                'latitude' => 49.316171,
                'longitude' => -117.663574,
            ],
            112 => [
                'name' => 'Nelson',
                'state' => 'British Columbia',
                'latitude' => 49.494891,
                'longitude' => -117.290039,
            ],
            113 => [
                'name' => 'Kimberley',
                'state' => 'British Columbia',
                'latitude' => 49.6850876,
                'longitude' => -115.9819477,
            ],
            114 => [
                'name' => 'Cranbrook',
                'state' => 'British Columbia',
                'latitude' => 49.5107477,
                'longitude' => -115.7672772,
            ],
            115 => [
                'name' => 'Fernie',
                'state' => 'British Columbia',
                'latitude' => 49.5041747,
                'longitude' => -115.062867,
            ],
            116 => [
                'name' => 'Lethbridge',
                'state' => 'Alberta',
                'latitude' => 49.6945782,
                'longitude' => -112.8331033,
            ],
            117 => [
                'name' => 'Williams Lake',
                'state' => 'British Columbia',
                'latitude' => 52.1292657,
                'longitude' => -122.1397259,
            ],
            118 => [
                'name' => 'Quesnel',
                'state' => 'British Columbia',
                'latitude' => 52.9794279,
                'longitude' => -122.493627,
            ],
            119 => [
                'name' => 'Kamloops',
                'state' => 'British Columbia',
                'latitude' => 50.6758269,
                'longitude' => -120.339415,
            ],
            120 => [
                'name' => 'Revelstoke',
                'state' => 'British Columbia',
                'latitude' => 50.998045,
                'longitude' => -118.1956709,
            ],
            121 => [
                'name' => 'Prince George',
                'state' => 'British Columbia',
                'latitude' => 53.9128645,
                'longitude' => -122.7453699,
            ],
            122 => [
                'name' => 'Dawson Creek',
                'state' => 'British Columbia',
                'latitude' => 55.7605306,
                'longitude' => -120.2364453,
            ],
            123 => [
                'name' => 'Grande Prairie',
                'state' => 'Alberta',
                'latitude' => 55.17108,
                'longitude' => -118.7949873,
            ],
            124 => [
                'name' => 'Airdrie',
                'state' => 'Alberta',
                'latitude' => 51.28597,
                'longitude' => -114.01062,
            ],
            125 => [
                'name' => 'Calgary',
                'state' => 'Alberta',
                'latitude' => 51.0456064,
                'longitude' => -114.0575418,
            ],
            126 => [
                'name' => 'Red Deer',
                'state' => 'Alberta',
                'latitude' => 52.2690628,
                'longitude' => -113.8141464,
            ],
            127 => [
                'name' => 'Lacombe',
                'state' => 'Alberta',
                'latitude' => 52.4727515,
                'longitude' => -113.733215,
            ],
            128 => [
                'name' => 'Wetaskiwin',
                'state' => 'Alberta',
                'latitude' => 52.968492,
                'longitude' => -113.36792,
            ],
            129 => [
                'name' => 'Leduc',
                'state' => 'Alberta',
                'latitude' => 53.2607825,
                'longitude' => -113.5511681,
            ],
            130 => [
                'name' => 'Camrose',
                'state' => 'Alberta',
                'latitude' => 53.013131,
                'longitude' => -112.840576,
            ],
            131 => [
                'name' => 'Spruce Grove',
                'state' => 'Alberta',
                'latitude' => 53.545204,
                'longitude' => -113.903503,
            ],
            132 => [
                'name' => 'St. Albert',
                'state' => 'Alberta',
                'latitude' => 53.633239,
                'longitude' => -113.628845,
            ],
            133 => [
                'name' => 'Edmonton',
                'state' => 'Alberta',
                'latitude' => 53.5462055,
                'longitude' => -113.491241,
            ],
            134 => [
                'name' => 'Sherwood Park',
                'state' => 'Alberta',
                'latitude' => 53.5256963,
                'longitude' => -113.296631,
            ],
            135 => [
                'name' => 'Fort Saskatchewan',
                'state' => 'Alberta',
                'latitude' => 53.7128571,
                'longitude' => -113.2148942,
            ],
            136 => [
                'name' => 'Fort St. John',
                'state' => 'British Columbia',
                'latitude' => 56.2524039,
                'longitude' => -120.846943,
            ],
            137 => [
                'name' => 'Yellowknife',
                'state' => 'Northwest Territories',
                'latitude' => 62.4540807,
                'longitude' => -114.377385,
            ],
            138 => [
                'name' => 'Brooks',
                'state' => 'Alberta',
                'latitude' => 50.571027,
                'longitude' => -111.893005,
            ],
            139 => [
                'name' => 'Medicine Hat',
                'state' => 'Alberta',
                'latitude' => 50.04303,
                'longitude' => -110.679016,
            ],
            140 => [
                'name' => 'Swift Current',
                'state' => 'Saskatchewan',
                'latitude' => 50.2849138,
                'longitude' => -107.7984496,
            ],
            141 => [
                'name' => 'Moose Jaw',
                'state' => 'Saskatchewan',
                'latitude' => 50.401515,
                'longitude' => -105.542908,
            ],
            142 => [
                'name' => 'Regina',
                'state' => 'Saskatchewan',
                'latitude' => 50.44876,
                'longitude' => -104.61731,
            ],
            143 => [
                'name' => 'Estevan',
                'state' => 'Saskatchewan',
                'latitude' => 49.1428076,
                'longitude' => -102.9910752,
            ],
            144 => [
                'name' => 'Weyburn',
                'state' => 'Saskatchewan',
                'latitude' => 49.6651238,
                'longitude' => -103.854034,
            ],
            145 => [
                'name' => 'Lloydminster',
                'state' => 'Saskatchewan',
                'latitude' => 53.279995,
                'longitude' => -110.00885,
            ],
            146 => [
                'name' => 'North Battleford',
                'state' => 'Saskatchewan',
                'latitude' => 52.776186,
                'longitude' => -108.300476,
            ],
            147 => [
                'name' => 'Cold Lake',
                'state' => 'Alberta',
                'latitude' => 54.46046,
                'longitude' => -110.192871,
            ],
            148 => [
                'name' => 'Meadow Lake',
                'state' => 'Saskatchewan',
                'latitude' => 54.13026,
                'longitude' => -108.435059,
            ],
            149 => [
                'name' => 'Saskatoon',
                'state' => 'Saskatchewan',
                'latitude' => 52.131802,
                'longitude' => -106.660767,
            ],
            150 => [
                'name' => 'Prince Albert',
                'state' => 'Saskatchewan',
                'latitude' => 53.201097,
                'longitude' => -105.748901,
            ],
            151 => [
                'name' => 'Humboldt',
                'state' => 'Saskatchewan',
                'latitude' => 52.202009,
                'longitude' => -105.1230368,
            ],
            152 => [
                'name' => 'Melfort',
                'state' => 'Saskatchewan',
                'latitude' => 52.8613707,
                'longitude' => -104.6135544,
            ],
            153 => [
                'name' => 'Melville',
                'state' => 'Saskatchewan',
                'latitude' => 50.9307241,
                'longitude' => -102.807296,
            ],
            154 => [
                'name' => 'Yorkton',
                'state' => 'Saskatchewan',
                'latitude' => 51.212045,
                'longitude' => -102.461243,
            ],
            155 => [
                'name' => 'Flin Flon',
                'state' => 'Manitoba',
                'latitude' => 54.769801,
                'longitude' => -101.878967,
            ],
            156 => [
                'name' => 'Brandon',
                'state' => 'Manitoba',
                'latitude' => 49.8511143,
                'longitude' => -99.9608924,
            ],
            157 => [
                'name' => 'Morden',
                'state' => 'Manitoba',
                'latitude' => 49.1927055,
                'longitude' => -98.1014567,
            ],
            158 => [
                'name' => 'Winkler',
                'state' => 'Manitoba',
                'latitude' => 49.187089,
                'longitude' => -97.937622,
            ],
            159 => [
                'name' => 'Winnipeg',
                'state' => 'Manitoba',
                'latitude' => 49.8955367,
                'longitude' => -97.1384584,
            ],
            160 => [
                'name' => 'Portage la Prairie',
                'state' => 'Manitoba',
                'latitude' => 49.972422,
                'longitude' => -98.289185,
            ],
            161 => [
                'name' => 'Steinbach',
                'state' => 'Manitoba',
                'latitude' => 49.530557,
                'longitude' => -96.69342,
            ],
            162 => [
                'name' => 'Selkirk',
                'state' => 'Manitoba',
                'latitude' => 50.146986,
                'longitude' => -96.880188,
            ],
            163 => [
                'name' => 'Kenora',
                'state' => 'Ontario',
                'latitude' => 49.766215,
                'longitude' => -94.4893528,
            ],
            164 => [
                'name' => 'Dryden',
                'state' => 'Ontario',
                'latitude' => 49.785698,
                'longitude' => -92.835846,
            ],
            165 => [
                'name' => 'Dauphin',
                'state' => 'Manitoba',
                'latitude' => 51.153509,
                'longitude' => -100.04425,
            ],
            166 => [
                'name' => 'Thompson',
                'state' => 'Manitoba',
                'latitude' => 55.743347,
                'longitude' => -97.863464,
            ],
            167 => [
                'name' => 'Fort McMurray',
                'state' => 'Alberta',
                'latitude' => 56.7291997,
                'longitude' => -111.3885221,
            ],
            168 => [
                'name' => 'Churchill',
                'state' => 'Manitoba',
                'latitude' => 58.7693101,
                'longitude' => -94.1736843,
            ],
            169 => [
                'name' => 'Windsor',
                'state' => 'Ontario',
                'latitude' => 42.3167397,
                'longitude' => -83.0373389,
            ],
            170 => [
                'name' => 'Chatham',
                'state' => 'Ontario',
                'latitude' => 42.4057219,
                'longitude' => -82.1853837,
            ],
            171 => [
                'name' => 'Sarnia',
                'state' => 'Ontario',
                'latitude' => 42.9743821,
                'longitude' => -82.403533,
            ],
            172 => [
                'name' => 'St. Thomas',
                'state' => 'Ontario',
                'latitude' => 42.779022,
                'longitude' => -81.1929882,
            ],
            173 => [
                'name' => 'London',
                'state' => 'Ontario',
                'latitude' => 42.9832406,
                'longitude' => -81.243372,
            ],
            174 => [
                'name' => 'Stratford',
                'state' => 'Ontario',
                'latitude' => 43.3700899,
                'longitude' => -80.9818016,
            ],
            175 => [
                'name' => 'Woodstock',
                'state' => 'Ontario',
                'latitude' => 43.1301111,
                'longitude' => -80.7562977,
            ],
            176 => [
                'name' => 'Brantford',
                'state' => 'Ontario',
                'latitude' => 43.1408157,
                'longitude' => -80.2631733,
            ],
            177 => [
                'name' => 'Waterloo',
                'state' => 'Ontario',
                'latitude' => 43.4652699,
                'longitude' => -80.5222961,
            ],
            178 => [
                'name' => 'Cambridge',
                'state' => 'Ontario',
                'latitude' => 43.3600536,
                'longitude' => -80.3123023,
            ],
            179 => [
                'name' => 'Kitchener',
                'state' => 'Ontario',
                'latitude' => 43.451291,
                'longitude' => -80.4927815,
            ],
            180 => [
                'name' => 'Guelph',
                'state' => 'Ontario',
                'latitude' => 43.5460516,
                'longitude' => -80.2493276,
            ],
            181 => [
                'name' => 'Hamilton',
                'state' => 'Ontario',
                'latitude' => 43.2560802,
                'longitude' => -79.8728583,
            ],
            182 => [
                'name' => 'Burlington',
                'state' => 'Ontario',
                'latitude' => 43.3248924,
                'longitude' => -79.7966835,
            ],
            183 => [
                'name' => 'Oakville',
                'state' => 'Ontario',
                'latitude' => 43.447436,
                'longitude' => -79.666672,
            ],
            184 => [
                'name' => 'Mississauga',
                'state' => 'Ontario',
                'latitude' => 43.5896231,
                'longitude' => -79.6443879,
            ],
            185 => [
                'name' => 'Welland',
                'state' => 'Ontario',
                'latitude' => 42.9922181,
                'longitude' => -79.2484192,
            ],
            186 => [
                'name' => 'Thorold',
                'state' => 'Ontario',
                'latitude' => 43.1249127,
                'longitude' => -79.2005935,
            ],
            187 => [
                'name' => 'St. Catharines',
                'state' => 'Ontario',
                'latitude' => 43.1579812,
                'longitude' => -79.2441003,
            ],
            188 => [
                'name' => 'Niagara Falls',
                'state' => 'Ontario',
                'latitude' => 43.1065603,
                'longitude' => -79.0639039,
            ],
            189 => [
                'name' => 'Owen Sound',
                'state' => 'Ontario',
                'latitude' => 44.5678105,
                'longitude' => -80.9430094,
            ],
            190 => [
                'name' => 'Brampton',
                'state' => 'Ontario',
                'latitude' => 43.685832,
                'longitude' => -79.7599366,
            ],
            191 => [
                'name' => 'Vaughan',
                'state' => 'Ontario',
                'latitude' => 43.7941544,
                'longitude' => -79.5268023,
            ],
            192 => [
                'name' => 'Newmarket',
                'state' => 'Ontario',
                'latitude' => 44.056258,
                'longitude' => -79.461708,
            ],
            193 => [
                'name' => 'Markham',
                'state' => 'Ontario',
                'latitude' => 43.8563707,
                'longitude' => -79.3376825,
            ],
            194 => [
                'name' => 'Toronto',
                'state' => 'Ontario',
                'latitude' => 43.6534817,
                'longitude' => -79.3839347,
            ],
            195 => [
                'name' => 'Richmond Hill',
                'state' => 'Ontario',
                'latitude' => 43.8801166,
                'longitude' => -79.4392925,
            ],
            196 => [
                'name' => 'Pickering',
                'state' => 'Ontario',
                'latitude' => 43.835765,
                'longitude' => -79.090576,
            ],
            197 => [
                'name' => 'Ajax',
                'state' => 'Ontario',
                'latitude' => 43.8505287,
                'longitude' => -79.0208814,
            ],
            198 => [
                'name' => 'Whitby',
                'state' => 'Ontario',
                'latitude' => 43.87982,
                'longitude' => -78.9421751,
            ],
            199 => [
                'name' => 'Oshawa',
                'state' => 'Ontario',
                'latitude' => 43.8975558,
                'longitude' => -78.8635324,
            ],
            200 => [
                'name' => 'Barrie',
                'state' => 'Ontario',
                'latitude' => 44.3893113,
                'longitude' => -79.6901736,
            ],
            201 => [
                'name' => 'Orillia',
                'state' => 'Ontario',
                'latitude' => 44.6092059,
                'longitude' => -79.4175587,
            ],
            202 => [
                'name' => 'Quinte West',
                'state' => 'Ontario',
                'latitude' => 44.0988246,
                'longitude' => -77.5748551,
            ],
            203 => [
                'name' => 'Belleville',
                'state' => 'Ontario',
                'latitude' => 44.1633264,
                'longitude' => -77.3852556,
            ],
            204 => [
                'name' => 'Kawartha Lakes',
                'state' => 'Ontario',
                'latitude' => 44.3596825,
                'longitude' => -78.7421729,
            ],
            205 => [
                'name' => 'Peterborough',
                'state' => 'Ontario',
                'latitude' => 44.3048009,
                'longitude' => -78.3199496,
            ],
            206 => [
                'name' => 'Kingston',
                'state' => 'Ontario',
                'latitude' => 44.230687,
                'longitude' => -76.481323,
            ],
            207 => [
                'name' => 'Brockville',
                'state' => 'Ontario',
                'latitude' => 44.5895925,
                'longitude' => -75.6843332,
            ],
            208 => [
                'name' => 'Bedford',
                'state' => 'Nova Scotia',
                'latitude' => 44.7303901,
                'longitude' => -63.6582365,
            ],
            209 => [
                'name' => 'Halifax',
                'state' => 'Nova Scotia',
                'latitude' => 44.648618,
                'longitude' => -63.5859487,
            ],
            210 => [
                'name' => 'Dartmouth',
                'state' => 'Nova Scotia',
                'latitude' => 44.6799707,
                'longitude' => -63.5720232,
            ],
            211 => [
                'name' => 'Thunder Bay',
                'state' => 'Ontario',
                'latitude' => 48.406414,
                'longitude' => -89.259796,
            ],
            212 => [
                'name' => 'Elliot Lake',
                'state' => 'Ontario',
                'latitude' => 46.373464,
                'longitude' => -82.652893,
            ],
            213 => [
                'name' => 'Sault Ste. Marie',
                'state' => 'Ontario',
                'latitude' => 46.52391,
                'longitude' => -84.320068,
            ],
            214 => [
                'name' => 'North Bay',
                'state' => 'Ontario',
                'latitude' => 46.3092115,
                'longitude' => -79.4607617,
            ],
            215 => [
                'name' => 'Sudbury',
                'state' => 'Ontario',
                'latitude' => 46.49272,
                'longitude' => -80.991211,
            ],
            216 => [
                'name' => 'Temiskaming Shores',
                'state' => 'Ontario',
                'latitude' => 47.512563,
                'longitude' => -79.675598,
            ],
            217 => [
                'name' => 'Timmins',
                'state' => 'Ontario',
                'latitude' => 48.477473,
                'longitude' => -81.330414,
            ],
            218 => [
                'name' => 'Rouyn-Noranda',
                'state' => 'Québec',
                'latitude' => 48.2420524,
                'longitude' => -79.0205378,
            ],
            219 => [
                'name' => 'Pembroke',
                'state' => 'Ontario',
                'latitude' => 45.8260909,
                'longitude' => -77.113541,
            ],
            220 => [
                'name' => 'Gatineau',
                'state' => 'Québec',
                'latitude' => 45.4277659,
                'longitude' => -75.710976,
            ],
            221 => [
                'name' => 'Ottawa',
                'state' => 'Ontario',
                'latitude' => 45.4208777,
                'longitude' => -75.6901106,
            ],
            222 => [
                'name' => 'Cornwall',
                'state' => 'Ontario',
                'latitude' => 45.0184417,
                'longitude' => -74.728703,
            ],
            223 => [
                'name' => 'Mirabel',
                'state' => 'Québec',
                'latitude' => 45.6452452,
                'longitude' => -74.0731738,
            ],
            224 => [
                'name' => 'Saint-Jean-sur-Richelieu',
                'state' => 'Québec',
                'latitude' => 45.3056879,
                'longitude' => -73.2533401,
            ],
            225 => [
                'name' => 'Montréal',
                'state' => 'Québec',
                'latitude' => 45.5031824,
                'longitude' => -73.5698065,
            ],
            226 => [
                'name' => 'Laval',
                'state' => 'Québec',
                'latitude' => 45.5757802,
                'longitude' => -73.7530656,
            ],
            227 => [
                'name' => 'Longueuil',
                'state' => 'Québec',
                'latitude' => 45.521906,
                'longitude' => -73.4644578,
            ],
            228 => [
                'name' => 'Saint-Jérôme',
                'state' => 'Québec',
                'latitude' => 45.775426,
                'longitude' => -74.013176,
            ],
            229 => [
                'name' => 'Joliette',
                'state' => 'Québec',
                'latitude' => 46.0239798,
                'longitude' => -73.4419936,
            ],
            230 => [
                'name' => 'Val-d\'Or',
                'state' => 'Québec',
                'latitude' => 48.1023356,
                'longitude' => -77.7875715,
            ],
            231 => [
                'name' => 'Saint-Hyacinthe',
                'state' => 'Québec',
                'latitude' => 45.627484,
                'longitude' => -72.940636,
            ],
            232 => [
                'name' => 'Granby',
                'state' => 'Québec',
                'latitude' => 45.3990409,
                'longitude' => -72.721834,
            ],
            233 => [
                'name' => 'Sherbrooke',
                'state' => 'Québec',
                'latitude' => 45.403271,
                'longitude' => -71.889038,
            ],
            234 => [
                'name' => 'Sorel-Tracy',
                'state' => 'Québec',
                'latitude' => 46.0435235,
                'longitude' => -73.1165159,
            ],
            235 => [
                'name' => 'Drummondville',
                'state' => 'Québec',
                'latitude' => 45.8864303,
                'longitude' => -72.5018764,
            ],
            236 => [
                'name' => 'Trois-Rivières',
                'state' => 'Québec',
                'latitude' => 46.3432325,
                'longitude' => -72.5428485,
            ],
            237 => [
                'name' => 'Cookshire-Eaton',
                'state' => 'Québec',
                'latitude' => 45.4125001,
                'longitude' => -71.6290758,
            ],
            238 => [
                'name' => 'Saint-Georges',
                'state' => 'Québec',
                'latitude' => 46.122987,
                'longitude' => -70.671959,
            ],
            239 => [
                'name' => 'Shawinigan',
                'state' => 'Québec',
                'latitude' => 46.5396581,
                'longitude' => -72.7518637,
            ],
            240 => [
                'name' => 'Québec',
                'state' => 'Québec',
                'latitude' => 46.8137431,
                'longitude' => -71.2084061,
            ],
            241 => [
                'name' => 'Lévis',
                'state' => 'Québec',
                'latitude' => 46.8033114,
                'longitude' => -71.1778792,
            ],
            242 => [
                'name' => 'Edmundston',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 47.364409,
                'longitude' => -68.328094,
            ],
            243 => [
                'name' => 'Saguenay',
                'state' => 'Québec',
                'latitude' => 48.405959,
                'longitude' => -71.069183,
            ],
            244 => [
                'name' => 'Alma',
                'state' => 'Québec',
                'latitude' => 48.548887,
                'longitude' => -71.651459,
            ],
            245 => [
                'name' => 'Rivière-du-Loup',
                'state' => 'Québec',
                'latitude' => 47.8358164,
                'longitude' => -69.5368025,
            ],
            246 => [
                'name' => 'Rimouski',
                'state' => 'Québec',
                'latitude' => 48.450155,
                'longitude' => -68.529968,
            ],
            247 => [
                'name' => 'Matane',
                'state' => 'Québec',
                'latitude' => 48.8468773,
                'longitude' => -67.5295498,
            ],
            248 => [
                'name' => 'Baie-Comeau',
                'state' => 'Québec',
                'latitude' => 49.2118373,
                'longitude' => -68.1801406,
            ],
            249 => [
                'name' => 'Fredericton',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 45.963233,
                'longitude' => -66.6432356,
            ],
            250 => [
                'name' => 'Saint John',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 45.278752,
                'longitude' => -66.058044,
            ],
            251 => [
                'name' => 'Moncton',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 46.097995,
                'longitude' => -64.80011,
            ],
            252 => [
                'name' => 'Dieppe',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 46.0945258,
                'longitude' => -64.7354772,
            ],
            253 => [
                'name' => 'Miramichi',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 47.032695,
                'longitude' => -65.494995,
            ],
            254 => [
                'name' => 'Bathurst',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 47.626529,
                'longitude' => -65.654297,
            ],
            255 => [
                'name' => 'Summerside',
                'state' => 'Prince Edward Island',
                'latitude' => 46.394306,
                'longitude' => -63.789368,
            ],
            256 => [
                'name' => 'Charlottetown',
                'state' => 'Prince Edward Island',
                'latitude' => 46.234953,
                'longitude' => -63.132935,
            ],
            257 => [
                'name' => 'Campbellton',
                'state' => 'New Brunswick / Nouveau-Brunswick',
                'latitude' => 48.0046993,
                'longitude' => -66.6768648,
            ],
            258 => [
                'name' => 'Sept-Îles',
                'state' => 'Québec',
                'latitude' => 50.2109579,
                'longitude' => -66.3790642,
            ],
            259 => [
                'name' => 'Sydney',
                'state' => 'Nova Scotia',
                'latitude' => 46.137977,
                'longitude' => -60.194092,
            ],
            260 => [
                'name' => 'Corner Brook',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 48.95317,
                'longitude' => -57.947388,
            ],
            261 => [
                'name' => 'St. John\'s',
                'state' => 'Newfoundland and Labrador',
                'latitude' => 47.5614705,
                'longitude' => -52.7126162,
            ],
        ];
    }
}
