extend type Query @guard {
    duplicateOrders(
        where: _ @whereConditions(columns: ["order_types_id", "companies_id", "created_at"])
        orderBy: _ @orderBy(columns: ["created_at", "order_number"])
    ): [Order!]!
        @paginate(
            model: "Kanvas\\Souk\\Orders\\Models\\Order"
            scopes: ["fromApp", "fromCompany", "notDeleted", "duplicate"]
            defaultCount: 25
        )
}

extend type Query @guard {
    orderActivityLogs(
        order_number: String
        where: _ @whereConditions(columns: ["description", "event", "causer_id", "created_at"])
        orderBy: _ @orderBy(columns: ["id", "created_at"])
    ): [ActivityLog!]!
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Souk\\Queries\\Orders\\OrderActivityLogQuery@getCompanyBuilder"
        )
}

extend type Mutation @guard {
    amendOrder(
        order_id: ID!
        correction_type: String!
        reason: String!
        evidence_urls: [String!]
        data: Mixed
    ): Order!
        @field(
            resolver: "App\\GraphQL\\Souk\\Mutations\\Orders\\OrderCorrectionMutation@amend"
        )
}
