<?php

declare(strict_types=1);

namespace Tests\Intelligence\Agents\Tools;

use Kanvas\Apps\Models\Apps;
use Kanvas\Guild\Leads\Models\Lead;
use Kanvas\Intelligence\Agents\Neuron\Tools\Social\AddMessageToChannelTool;
use Kanvas\Intelligence\Agents\Neuron\Tools\Social\CreateEntityChannelTool;
use Kanvas\Intelligence\Agents\Neuron\Tools\Social\CreateMessageTool;
use Kanvas\Social\Channels\Models\Channel;
use Kanvas\Social\Messages\Models\Message;
use Kanvas\SystemModules\Repositories\SystemModulesRepository;
use Tests\TestCase;

class SocialMessageToolsTest extends TestCase
{
    public function testCreatesMessageThenAttachesItToAnEntityChannel(): void
    {
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();
        $lead = Lead::factory()
            ->withAppId($app->getId())
            ->withCompanyId($company->getId())
            ->create();
        SystemModulesRepository::getByModelName(Lead::class, $app);

        $channelTool = new CreateEntityChannelTool($app, $company, $user);
        $channelResult = $channelTool->__invoke(
            entity_namespace: Lead::class,
            entity_id: (string) $lead->getId(),
            name: 'Agent SMS ' . $lead->getId(),
            slug: 'agent-sms-' . $lead->getId(),
        );

        $this->assertSame('success', $channelResult['status']);

        $messageTool = new CreateMessageTool($app, $company, $user);
        $messageResult = $messageTool->__invoke('Message generated by a sub-agent');

        $this->assertSame('success', $messageResult['status']);

        $message = Message::findOrFail($messageResult['message_id']);
        $channel = Channel::findOrFail($channelResult['channel_id']);

        $this->assertSame([], $message->channels()->pluck('channels.id')->all());
        $this->assertSame((string) $lead->getId(), (string) $channel->entity_id);
        $this->assertSame(Lead::class, $channel->entity_namespace);

        $attachTool = new AddMessageToChannelTool($app, $company);
        $attachResult = $attachTool->__invoke($message->getId(), $channel->getId());

        $this->assertSame('success', $attachResult['status']);
        $this->assertTrue($channel->messages()->whereKey($message->getId())->exists());
        $this->assertSame($message->getId(), $channel->fresh()->last_message_id);
    }

    public function testEntityChannelCreationIsIdempotent(): void
    {
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();
        $lead = Lead::factory()
            ->withAppId($app->getId())
            ->withCompanyId($company->getId())
            ->create();
        SystemModulesRepository::getByModelName(Lead::class, $app);
        $tool = new CreateEntityChannelTool($app, $company, $user);
        $arguments = [
            'entity_namespace' => Lead::class,
            'entity_id' => (string) $lead->getId(),
            'name' => 'Idempotent channel',
            'slug' => 'idempotent-' . $lead->getId(),
        ];

        $first = $tool->__invoke(...$arguments);
        $second = $tool->__invoke(...$arguments);

        $this->assertSame('success', $first['status']);
        $this->assertSame($first['channel_id'], $second['channel_id']);
    }

    public function testRejectsEmptyMessageAndUnknownTenantRecords(): void
    {
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $empty = new CreateMessageTool($app, $company, $user)
            ->__invoke('   ');
        $missing = new AddMessageToChannelTool($app, $company)
            ->__invoke(PHP_INT_MAX, PHP_INT_MAX);

        $this->assertSame('error', $empty['status']);
        $this->assertSame('error', $missing['status']);
    }
}
