version: "3.8"

x-common-queue-settings: &common-queue-settings
  restart: always
  image: php-app-image # Use the built image for all the services
  extra_hosts:
    - "host.docker.internal:host-gateway"
  command:
    - "sh"
    - "-c"
    - "php artisan config:cache && php artisan queue:work --tries=0 --queue=default,notifications,kanvas-social,batch-logger,imports --timeout=3750"
  environment:
    WWWUSER: "${WWWUSER}"
    LARAVEL_SAIL: 1
    XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
    XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
  volumes:
    - ".:/var/www/html"
    - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
  networks:
    - sail

services:
  php:
    container_name: php${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: development.Dockerfile
    image: php-app-image # Build the image here and tag it
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    command:
      - "sh"
      - "-c"
      - "php artisan octane:start --server=swoole --task-workers=10"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
      - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
    networks:
      - sail

  queue:
    <<: *common-queue-settings
    container_name: queue

  batch-logger-queue:
    <<: *common-queue-settings
    container_name: batch-logger-queue
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=batch-logger --tries=0 --timeout=3750"

  queue-social:
    <<: *common-queue-settings
    container_name: queue-social
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=kanvas-social --tries=0 --timeout=3750"

  queue-notifications:
    <<: *common-queue-settings
    container_name: queue-notifications
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=notifications --tries=0 --timeout=3750"

  queue-user-interactions:
    <<: *common-queue-settings
    container_name: queue-user-interactions
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=user-interactions --tries=0 --timeout=3750"

  queue-imports:
    <<: *common-queue-settings
    container_name: queue-imports
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=imports --tries=0 --timeout=3750"
  queue-scrapper:
    <<: *common-queue-settings
    container_name: queue-scrapper
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=scrapper-queue --tries=0 --timeout=3750"
  queue-scrapper-worker-1:
    <<: *common-queue-settings
    container_name: queue-scrapper-worker-1
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=scrapper-queue --tries=0 --timeout=3750"
  queue-scrapper-worker-2:
    <<: *common-queue-settings
    container_name: queue-scrapper-worker-2
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=scrapper-queue --tries=0 --timeout=3750"
  queue-scrapper-worker-3:
    <<: *common-queue-settings
    container_name: queue-scrapper-worker-3
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=scrapper-queue --tries=0 --timeout=3750"
  queue-scrapper-worker-4:
    <<: *common-queue-settings
    container_name: queue-scrapper-worker-4
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=scrapper-queue --tries=0 --timeout=3750"
  queue-sync-shopify:
    <<: *common-queue-settings
    container_name: queue-sync-shopify-queue
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=sync-shopify-queue --tries=0 --timeout=3750"
  queue-sync-shopify-worker-1:
    <<: *common-queue-settings
    container_name: queue-sync-shopify-queue-worker-1
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=sync-shopify-queue --tries=0 --timeout=3750"
  queue-sync-shopify-worker-2:
    <<: *common-queue-settings
    container_name: queue-sync-shopify-queue-worker-2
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=sync-shopify-queue --tries=0 --timeout=3750"
  queue-scout-worker-1:
    <<: *common-queue-settings
    container_name: queue-scout-worker-1
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue scout --tries=0 --timeout=3750"
  queue-scout-worker-2:
    <<: *common-queue-settings
    container_name: queue-scout-worker-2
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue scout --tries=0 --timeout=3750"
  queue-scout-worker-3:
    <<: *common-queue-settings
    container_name: queue-scout-worker-3
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue scout --tries=0 --timeout=3750"
  queue-workflow-1:
    <<: *common-queue-settings
    container_name: queue-workflow-1
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=workflow --tries=0 --timeout=3750"
  queue-workflow-2:
    <<: *common-queue-settings
    container_name: queue-workflow-2
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=workflow --tries=0 --timeout=3750"
  queue-workflow-3:
    <<: *common-queue-settings
    container_name: queue-workflow-3
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue=workflow --tries=0 --timeout=3750"

  laravel-scheduler:
    container_name: laravel-scheduler
    restart: always
    image: php-app-image # Use the same image for the scheduler
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan schedule:work"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
      - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
    networks:
      - sail

  nginx:
    image: nginx:latest
    container_name: nginx${APP_CONTAINER_NAME}
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ".:/var/www/html"
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      retries: 3
      timeout: 5s

  # redis:
  #   container_name: redis${APP_CONTAINER_NAME}
  #   image: "redis:alpine"
  #   ports:
  #     - "${FORWARD_REDIS_PORT:-6379}:6379"
  #   volumes:
  #     - "sail-redis:/data"
  #   networks:
  #     - sail
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     retries: 3
  #     timeout: 5s

#  puppeteer:
#    image: browserless/chrome
#    container_name: puppeteer${APP_CONTAINER_NAME}
#    environment:
      # Enable preloading to optimize performance
      #- PREBOOT_CHROME=true
      # Optional: Define the max concurrency if required
      #- MAX_CONCURRENT_SESSIONS=10
      # Optional: You can set a custom token for API security
      # - TOKEN=your_secure_token
#    ports:
     # - "3000:3000" # Expose Puppeteer API on port 3000
#    restart: always
#    networks:
#      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-redis:
    driver: local
