version: '3.8'

x-common-queue-settings: &common-queue-settings
  restart: always
  build:
    context: .
    dockerfile: development.Dockerfile
  extra_hosts:
    - "host.docker.internal:host-gateway"
  command: 
    - "sh"
    - "-c"
    - "php artisan config:cache && php artisan queue:work --tries=3 --timeout=3750"
  environment:
    WWWUSER: "${WWWUSER}"
    LARAVEL_SAIL: 1
    XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
    XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
  volumes:
    - ".:/var/www/html"
    - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
  networks:
    - sail

services:
  php:
    container_name: php${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: development.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: 
    - "sh"
    - "-c"
    - "php artisan octane:start --server=swoole"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
      - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
    networks:
      - sail

  queue:
    <<: *common-queue-settings
    container_name: queue

  queue2:
    <<: *common-queue-settings
    container_name: queue2

  queue3:
    <<: *common-queue-settings
    container_name: queue3

  queue4:
    <<: *common-queue-settings
    container_name: queue4

  queue5:
    <<: *common-queue-settings
    container_name: queue5

  queue6:
    <<: *common-queue-settings
    container_name: queue6

  batch-logger-queue:
    <<: *common-queue-settings
    container_name: batch-logger-queue
    command: 
        - "sh"
        - "-c"
        - "php artisan config:cache && php artisan queue:work --queue=batch-logger --tries=3 --timeout=3750"

  queue-social:
    <<: *common-queue-settings
    container_name: queue-social
    command: 
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue kanvas-social --tries=3 --timeout=3750"

  queue-notifications:
    <<: *common-queue-settings
    container_name: queue-notifications
    command: 
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan queue:work --queue notifications --tries=3 --timeout=3750"

  laravel-scheduler:
    container_name: laravel-scheduler
    restart: always
    build:
      context: .
      dockerfile: development.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "sh"
      - "-c"
      - "php artisan config:cache && php artisan schedule:work"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - ".:/var/www/html"
      - ./docker/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php.ini:/usr/local/etc/php/conf.d/xz-custom.ini
    networks:
      - sail

  nginx:
    image: nginx:latest
    container_name: nginx${APP_CONTAINER_NAME}
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ".:/var/www/html"
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sail
    depends_on:
      - php
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      retries: 3
      timeout: 5s

  redis:
    container_name: redis${APP_CONTAINER_NAME}
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "sail-redis:/data"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sail-redis:
    driver: local