<?php

declare(strict_types=1);

namespace Kanvas\Connectors\BrushCrazy\Enums;

/**
 * External-id keys written to `apps_custom_fields`. The (model_name, name) pair is what makes a
 * key unique, so the same case is reused across models — BRUSHCRAZY_USER_ID lives on People,
 * Participant and Facilitator without colliding.
 */
enum CustomFieldEnum: string
{
    case BRUSHCRAZY_STUDIO_ID = 'BRUSHCRAZY_STUDIO_ID';
    case BRUSHCRAZY_USER_ID = 'BRUSHCRAZY_USER_ID';
    case BRUSHCRAZY_PAINTING_ID = 'BRUSHCRAZY_PAINTING_ID';
    case BRUSHCRAZY_PRODUCT_ID = 'BRUSHCRAZY_PRODUCT_ID';

    /** Slug of name + price in cents — substrates are deduped into shared variants, not 1:1. */
    case BRUSHCRAZY_SUBSTRATE_KEY = 'BRUSHCRAZY_SUBSTRATE_KEY';

    case BRUSHCRAZY_SUBSTRATE_ID = 'BRUSHCRAZY_SUBSTRATE_ID';
    case BRUSHCRAZY_EVENT_GROUP_KEY = 'BRUSHCRAZY_EVENT_GROUP_KEY';

    /**
     * "{morph}:{id}" — lessons.id=5, events.id=5 and workshops.id=5 are three different objects,
     * and this is the exact shape `registrations.calendarable_type`/`calendarable_id` already
     * stores, so joins need no translation.
     */
    case BRUSHCRAZY_CALENDARABLE_KEY = 'BRUSHCRAZY_CALENDARABLE_KEY';

    case BRUSHCRAZY_REGISTRATION_ID = 'BRUSHCRAZY_REGISTRATION_ID';
    case BRUSHCRAZY_ATTENDEE_ID = 'BRUSHCRAZY_ATTENDEE_ID';
    case BRUSHCRAZY_SALE_ID = 'BRUSHCRAZY_SALE_ID';
    case BRUSHCRAZY_SALE_ITEM_ID = 'BRUSHCRAZY_SALE_ITEM_ID';
    case BRUSHCRAZY_MEDIA_ID = 'BRUSHCRAZY_MEDIA_ID';
    case BRUSHCRAZY_LOOKUP_KEY = 'BRUSHCRAZY_LOOKUP_KEY';
    case BRUSHCRAZY_SHIFT_ID = 'BRUSHCRAZY_SHIFT_ID';
    case BRUSHCRAZY_UNKNOWN_GUEST = 'BRUSHCRAZY_UNKNOWN_GUEST';

    case BRUSHCRAZY_STUDIO_TIMEZONE = 'BRUSHCRAZY_STUDIO_TIMEZONE';
    case BRUSHCRAZY_STUDIO_OCCUPANCY = 'BRUSHCRAZY_STUDIO_OCCUPANCY';
    case BRUSHCRAZY_STUDIO_SETTINGS = 'BRUSHCRAZY_STUDIO_SETTINGS';
    case BRUSHCRAZY_STUDIO_SALES_TAX = 'BRUSHCRAZY_STUDIO_SALES_TAX';
    case BRUSHCRAZY_STUDIO_BILLING = 'BRUSHCRAZY_STUDIO_BILLING';
    case BRUSHCRAZY_STUDIO_SOCIAL = 'BRUSHCRAZY_STUDIO_SOCIAL';
    case BRUSHCRAZY_STUDIO_LAT = 'BRUSHCRAZY_STUDIO_LAT';
    case BRUSHCRAZY_STUDIO_LNG = 'BRUSHCRAZY_STUDIO_LNG';
    case BRUSHCRAZY_DISPLAY_NAME = 'BRUSHCRAZY_DISPLAY_NAME';
    case BRUSHCRAZY_BIRTHDAY_DAY = 'BRUSHCRAZY_BIRTHDAY_DAY';
    case BRUSHCRAZY_POINTS = 'BRUSHCRAZY_POINTS';
    case BRUSHCRAZY_REWARDS = 'BRUSHCRAZY_REWARDS';
    case BRUSHCRAZY_FAVORITE_STUDIO_ID = 'BRUSHCRAZY_FAVORITE_STUDIO_ID';
    case BRUSHCRAZY_LAST_STUDIO_ID = 'BRUSHCRAZY_LAST_STUDIO_ID';
    case BRUSHCRAZY_ROLES = 'BRUSHCRAZY_ROLES';
    case BRUSHCRAZY_EMPLOYEE_POSITION = 'BRUSHCRAZY_EMPLOYEE_POSITION';
    case BRUSHCRAZY_PAINTING_SUBTITLE = 'BRUSHCRAZY_PAINTING_SUBTITLE';
    case BRUSHCRAZY_PAINTING_DIFFICULTY = 'BRUSHCRAZY_PAINTING_DIFFICULTY';
    case BRUSHCRAZY_PAINTING_DURATION = 'BRUSHCRAZY_PAINTING_DURATION';
    case BRUSHCRAZY_PAINTING_RECIPE = 'BRUSHCRAZY_PAINTING_RECIPE';
}
