<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Shopify\Enums;

enum CustomFieldEnum: string
{
    case SHOPIFY_API_CREDENTIAL = 'SHOPIFY_CREDENTIAL';
    case SHOPIFY_API_KEY = 'SHOPIFY_API_KEY';
    case SHOPIFY_API_SECRET = 'SHOPIFY_API_SECRET';
    case SHOP_URL = 'SHOPIFY_HOSTNAME';
    case SHOPIFY_PRODUCT_ID = 'SHOPIFY_PRODUCT_ID';
    case SHOPIFY_VARIANT_ID = 'SHOPIFY_VARIANT_ID';
    case SHOPIFY_META_FIELD_ID = 'SHOPIFY_META_FIELD_ID';
    case SHOPIFY_PRODUCT_URL = 'SHOPIFY_URL';
    case SHOPIFY_VARIANT_INVENTORY_ID = 'SHOPIFY_VARIANT_INVENTORY_ID';
    case SHOPIFY_CUSTOMER_ID = 'SHOPIFY_CUSTOMER_ID';
    case SHOPIFY_ORDER_ID = 'SHOPIFY_ORDER_ID';
    case USER_SHOPIFY_ID = 'shopify_id';
    case SHOPIFY_MANUEL_ORDER_NOTIFICATION_MSG = 'SHOPIFY_MANUEL_ORDER_NOTIFICATION_MSG';
}
