type Action {
    id: ID!
    name: String!
    slug: String!
    description: String
    companies_id: ID
    icon: Mixed
    form_fields: Mixed
    form_config: Mixed
    is_active: Boolean!
    is_published: Boolean!
    collects_info: Boolean!
    config: Mixed
    pipeline: ActionPipeline @belongsTo
    parent: Action @belongsTo(relation: "parent")
    children: [Action!] @hasMany(relation: "children")
}

type CompanyAction {
    id: ID!
    action: Action! @belongsTo
    company: Company! @belongsTo
    name: String!
    description: String
    config: Mixed
    form_config: Mixed
    pdf_config: Mixed
    status: String
    is_active: Boolean!
    is_published: Boolean!
    weight: Float!
    pipeline: ActionPipeline @belongsTo
    parent: CompanyAction @belongsTo(relation: "parent")
    children: [CompanyAction!] @hasMany(relation: "children")
    files: [Filesystem!]!
        @cacheRedis
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Ecosystem\\Queries\\Filesystem\\FilesystemQuery@getFileByGraphType"
        )
    custom_fields: [CustomField!]!
        @paginate(
            defaultCount: 25
            resolver: "App\\GraphQL\\Ecosystem\\Queries\\CustomFields\\CustomFieldQuery@getAllByGraphType"
        )
}

input ActionInput {
    name: String!
    description: String
    icon: Mixed
    form_fields: Mixed
    form_config: Mixed
    is_active: Boolean
    collects_info: Boolean
    is_published: Boolean
    pipelines_id: ID
    parent_id: ID
}

input UpdateActionInput {
    name: String!
    description: String
    icon: Mixed
    form_fields: Mixed
    form_config: Mixed
    is_active: Boolean
    collects_info: Boolean
    is_published: Boolean
    pipelines_id: ID
    parent_id: ID
}

input CreateCompanyActionInput {
    actions_id: ID!
    name: String!
    description: String
    form_config: Mixed
    config: Mixed
    is_active: Boolean
    is_published: Boolean
    weight: Float
    parent_id: ID
}

input UpdateCompanyActionInput {
    name: String!
    description: String
    config: Mixed
    form_config: Mixed
    status: String
    is_active: Boolean
    is_published: Boolean
    weight: Float
    parent_id: ID
}

extend type Mutation @guardByAdmin {
    createAction(input: ActionInput!): Action!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\ActionMutation@create"
        )
    updateAction(id: ID!, input: UpdateActionInput!): Action!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\ActionMutation@update"
        )
    deleteAction(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\ActionMutation@delete"
        )
    createCompanyAction(input: CreateCompanyActionInput!): CompanyAction!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\CompanyActionMutation@create"
        )
    updateCompanyAction(id: ID!, input: UpdateCompanyActionInput!): CompanyAction!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\CompanyActionMutation@update"
        )
    deleteCompanyAction(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Actions\\CompanyActionMutation@delete"
        )
}

extend type Query @guard {
    actionEngineActions(
        search: String @search
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "name"
                    "slug"
                    "is_active"
                    "is_published"
                    "pipelines_id"
                ]
            )
        orderBy: _
            @orderBy(
                columns: [
                    "id"
                    "created_at"
                    "updated_at"
                    "name"
                ]
            )
    ): [Action!]!
        @paginate(
            model: "Kanvas\\ActionEngine\\Actions\\Models\\Action"
            scopes: ["fromPublicApp", "notDeleted"]
            defaultCount: 25
        )

    companyActions(
        search: String @search
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "actions_id"
                    "companies_id"
                    "companies_branches_id"
                    "parent_id"
                    "path"
                    "pipelines_id"
                    "is_active"
                    "is_published"
                    "weight"
                ]
            )
        orderBy: _
            @orderBy(
                columns: [
                    "id"
                    "created_at"
                    "updated_at"
                    "weight"
                    "name"
                    "weight"
                    "is_default"
                ]
            )
    ): [CompanyAction!]!
        @paginate(
            model: "Kanvas\\ActionEngine\\Actions\\Models\\CompanyAction"
            scopes: ["fromCompany", "fromApp", "notDeleted"]
            defaultCount: 25
        )
}
