type ActionPipeline {
    id: ID!
    uuid: String!
    user: User! @belongsTo
    company: Company! @belongsTo
    stages: [ActionPipelineStage!]! @hasMany
    name: String!
    slug: String!
    weight: Int!
    is_default: Boolean!
    created_at: DateTime!
    updated_at: DateTime!
}

type ActionPipelineStage {
    id: ID!
    pipeline: ActionPipeline! @belongsTo
    name: String!
    slug: String!
    has_rotting_days: Int!
    rotting_days: Int!
    weight: Int!
}

input CreatePipelineInput {
    name: String!
    slug: String
    weight: Int
    is_default: Boolean
}

input UpdatePipelineInput {
    name: String!
    slug: String
    weight: Int
    is_default: Boolean
}

input CreatePipelineStageInput {
    pipelines_id: ID!
    name: String!
    has_rotting_days: Int
    rotting_days: Int
    weight: Int
}

input UpdatePipelineStageInput {
    name: String!
    has_rotting_days: Int
    rotting_days: Int
    weight: Int
}

extend type Mutation @guardByAdmin {
    createActionPipeline(input: CreatePipelineInput!): ActionPipeline!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineMutation@create"
        )
    updateActionPipeline(id: ID!, input: UpdatePipelineInput!): ActionPipeline!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineMutation@update"
        )
    deleteActionPipeline(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineMutation@delete"
        )
    createActionPipelineStage(
        input: CreatePipelineStageInput!
    ): ActionPipelineStage!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineStageMutation@create"
        )
    updateActionPipelineStage(
        id: ID!
        input: UpdatePipelineStageInput!
    ): ActionPipelineStage!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineStageMutation@update"
        )
    deleteActionPipelineStage(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\ActionEngine\\Mutations\\Pipelines\\PipelineStageMutation@delete"
        )
}

extend type Query @guard {
    actionPipelines(
        search: String @search
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "uuid"
                    "companies_id"
                    "slug"
                    "weight"
                    "is_default"
                ]
            )
        orderBy: _
            @orderBy(
                columns: [
                    "id"
                    "created_at"
                    "updated_at"
                    "weight"
                    "slug"
                    "name"
                    "weight"
                    "is_default"
                ]
            )
    ): [ActionPipeline!]!
        @paginate(
            model: "Kanvas\\ActionEngine\\Pipelines\\Models\\Pipeline"
            scopes: ["fromCompany", "fromApp", "notDeleted"]
            defaultCount: 25
        )
}
