<div style="font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #111; max-width: 720px;">
    <h1 style="margin-bottom: 4px;">Daily agent learning — {{ $cycle_date }}</h1>
    <p style="color: #555; margin-top: 0;">
        {{ $company_name }} · {{ count($agents) }} agent{{ count($agents) === 1 ? '' : 's' }} active yesterday
    </p>

    @if (count($agents) === 0)
        <p>No agent activity recorded for this date.</p>
    @endif

    @foreach ($agents as $agent)
        <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 24px 0;">

        <h2 style="margin-bottom: 4px;">{{ $agent['name'] }}</h2>
        <p style="color: #666; font-size: 13px; margin-top: 0;">
            {{ $agent['conversation_count'] }} conversation{{ $agent['conversation_count'] === 1 ? '' : 's' }}
            · self-improvement score {{ number_format((float) $agent['self_improvement_score'], 2) }}
            @if (! empty($agent['pushed_to_runtime']))
                · learnings pushed to runtime
            @endif
        </p>

        @if (! empty($agent['briefing']))
            <h3 style="margin-bottom: 4px;">Morning briefing</h3>
            <div style="white-space: pre-wrap; line-height: 1.5;">{{ $agent['briefing'] }}</div>
        @endif

        @if (! empty($agent['proposed_actions']))
            <h3 style="margin-bottom: 4px; margin-top: 16px;">Today's proposed actions</h3>
            <ul style="margin-top: 0;">
                @foreach ($agent['proposed_actions'] as $action)
                    <li>{{ $action }}</li>
                @endforeach
            </ul>
        @endif

        @if (! empty($agent['durable_facts']))
            <h3 style="margin-bottom: 4px; margin-top: 16px;">New durable facts written to memory</h3>
            <ul style="margin-top: 0;">
                @foreach ($agent['durable_facts'] as $fact)
                    <li>{{ $fact }}</li>
                @endforeach
            </ul>
        @endif

        @if (! empty($agent['skills_emerged']))
            <h3 style="margin-bottom: 4px; margin-top: 16px;">Skills emerged</h3>
            <ul style="margin-top: 0;">
                @foreach ($agent['skills_emerged'] as $skill)
                    <li>
                        <strong>{{ $skill['name'] ?? 'unknown' }}</strong>
                        — confidence {{ number_format((float) ($skill['confidence'] ?? 0), 2) }}
                    </li>
                @endforeach
            </ul>
        @endif

        @if (! empty($agent['signed_by_text']))
            <p style="color: #888; font-style: italic; margin-top: 12px;">{{ $agent['signed_by_text'] }}</p>
        @endif
    @endforeach

    <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 32px 0 16px;">
    <p style="color: #999; font-size: 12px;">
        Generated by the Nervous System daily-learning scheduler.
    </p>
</div>
