<?php

declare(strict_types=1);

namespace Tests\Connectors\Integration\Intellicheck;

use Kanvas\Apps\Models\Apps;
use Kanvas\Connectors\Intellicheck\Services\IdVerificationService;
use Kanvas\Connectors\Intellicheck\Services\PeopleService;
use Kanvas\Guild\Customers\Models\People;
use Kanvas\Guild\Leads\Models\Lead;
use Tests\TestCase;

final class IdVerificationTest extends TestCase
{
    protected function idVerificationData(): array
    {
        return [
            'is_showroom' => true,
            'idcheck' => [
                'data' => [
                    'uniqueID' => 2119,
                    'weightPounds' => null,
                    'heightFeetInches' => "5' 7\"",
                    'age' => 40,
                    'driverClass' => 'E',
                    'restrictions' => 'A',
                    'address1' => '10405 Sw 112th St',
                    'dLIDNumberRaw' => 'K523503856060',
                    'endorsements' => null,
                    'address2' => null,
                    'organDonor' => 'Yes',
                    'socialSecurity' => null,
                    'city' => 'Miami',
                    'issueDate' => '03/22/2006',
                    'transactionIdentifier' => 'ad1014e4-50f3-49db-a35c-57a884311814',
                    'processResult' => 'DocumentUnknown',
                    'gender' => 'Female',
                    'isDuplicate' => 'No',
                    'firstName' => 'Keira',
                    'issuingJurisdictionAbbrv' => 'FL',
                    'middleName' => 'Christina',
                    'eyeColor' => null,
                    'expired' => 'Yes',
                    'docType' => null,
                    'hairColor' => null,
                    'expirationDate' => '03/26/2012',
                    'extendedResultCode' => 'U',
                    'docCategory' => 'DL',
                    'stateIssuerMismatch' => 'No',
                    'heightCentimeters' => '170',
                    'duplicateDate' => null,
                    'lastName' => 'Knightley',
                    'issuingJurisdictionCvt' => 'Florida',
                    'dLIDNumberFormatted' => 'K523-503-85-606-0',
                    'postalCode' => '33176-3425',
                    'state' => 'FL',
                    'dateOfBirth' => '03/26/1985',
                    'isRealID' => null,
                    'mediaType' => '2D',
                    'testCard' => false,
                    'weightKilograms' => null,
                ],
                'result' => true,
                'success' => true,
                'message' => null,
            ],
            'OCR' => [
                'result' => true,
                'data' => [
                    'documentNumber' => 'W730421894796',
                    'eyeColor' => null,
                    'weightKilograms' => null,
                    'firstName' => 'WARNER ALVIN',
                    'dateOfBirth' => '1988-06-23',
                    'dlEndorsement' => null,
                    'faceImageBase64' => null,
                    'dateOfBirthFormatted' => '06/23/1988',
                    'errorMessage' => null,
                    'dateOfExpiryFormatted' => '12/29/2018',
                    'countryCode' => 'USA',
                    'dateOfExpiry' => '2018-12-29',
                    'dateOfIssue' => '2011-06-25',
                    'dlClass' => null,
                    'fullDocumentImageBase64' => null,
                    'dlRestrictions' => null,
                    'placeOfBirth' => null,
                    'age' => null,
                    'dateOfIssueFormatted' => '06/25/2011',
                    'address' => '2537 WAYMAN RD MOORE HAVEN, FL 33471-0000',
                    'fullName' => 'WAH WARNER ALVIN',
                    'isRealID' => 'yes',
                    'sex' => 'X',
                    'documentRecognized' => 1,
                    'lastName' => 'WAH',
                    'nationality' => null,
                    'issuerName' => 'Florida',
                    'height' => '180',
                ],
                'message' => null,
                'success' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'addressMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                        'similarityScore' => 27,
                    ],
                    'isDocumentNumberMatch' => false,
                    'sexMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 0,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                    ],
                    'isDobMatch' => true,
                    'documentNumberMatchDetails' => [
                        'similarityScore' => 7,
                        'similarityThreshold' => 70,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                    ],
                    'isCountryCodeMatch' => null,
                    'dlClassMatchDetails' => [
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                        'similarityThreshold' => 70,
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 70,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                    ],
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 100,
                    ],
                    'isIssuerNameMatch' => true,
                    'dlRestrictionsMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'weightMatchDetails' => [
                        'details' => 'Missing value for comparison',
                        'similarityScore' => null,
                        'similarityThreshold' => 70,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 60,
                        'similarityThreshold' => 70,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                    ],
                    'isWeightMatch' => null,
                    'isIssueDateMatch' => false,
                    'realIdMatchDetails' => [
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                        'similarityThreshold' => 70,
                    ],
                    'eyeColorMatchDetails' => [
                        'details' => 'Missing value for comparison',
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                    ],
                    'dlEndorsementMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Missing value for comparison',
                        'similarityScore' => null,
                    ],
                    'isDlRestrictionsMatch' => null,
                    'isSexMatch' => false,
                    'isNationalityMatch' => null,
                    'isDlEndorsementMatch' => null,
                    'isRealIdMatch' => null,
                    'expirationDateMatchDetails' => [
                        'similarityScore' => 60,
                        'similarityThreshold' => 70,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                    ],
                    'nameMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Mismatch, similarity score is lower than similarity threshold',
                        'similarityScore' => 21,
                    ],
                    'isNameMatch' => false,
                    'heightMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 75,
                        'similarityThreshold' => 70,
                    ],
                    'isExpirationDateMatch' => false,
                    'isHeightMatch' => true,
                    'isAddressMatch' => false,
                    'isDlClassMatch' => null,
                    'isEyeColorMatch' => null,
                ],
                'success' => false,
                'message' => null,
                'result' => true,
            ],
            'ip' => '172.18.0.24',
        ];
    }

    public function idVerificationFlag(): array
    {
        return [
            'idcheck' => [
                'data' => [
                    'dLIDNumberRaw' => '000000000',
                    'heightFeetInches' => "5' 10\"",
                    'extendedResultCode' => 'Y',
                    'driverClass' => 'DM',
                    'endorsements' => null,
                    'expirationDate' => '11/11/2032',
                    'docCategory' => 'DL',
                    'city' => 'Knoxville',
                    'postalCode' => '37932-2288',
                    'issueDate' => '11/11/2024',
                    'duplicateDate' => null,
                    'mediaType' => '2D',
                    'uniqueID' => 6211,
                    'expired' => 'No',
                    'docType' => null,
                    'dateOfBirth' => '1981-11-02',
                    'lastName' => 'Testington',
                    'middleName' => 'Alan',
                    'weightKilograms' => null,
                    'restrictions' => null,
                    'gender' => 'Male',
                    'weightPounds' => null,
                    'isDuplicate' => 'No',
                    'organDonor' => 'Yes',
                    'age' => 43,
                    'socialSecurity' => null,
                    'state' => 'TN',
                    'processResult' => 'DocumentProcessOK',
                    'stateIssuerMismatch' => 'No',
                    'issuingJurisdictionAbbrv' => 'TN',
                    'hairColor' => null,
                    'dLIDNumberFormatted' => '000000000',
                    'transactionIdentifier' => '2cbb2fb1-b57f-4b8a-974c-09957866acd5',
                    'issuingJurisdictionCvt' => 'Tennessee',
                    'address2' => null,
                    'firstName' => 'John',
                    'testCard' => false,
                    'eyeColor' => 'Blue',
                    'isRealID' => 'Yes',
                    'heightCentimeters' => '178',
                    'address1' => '1144 Belle Pond Ave',
                ],
                'message' => null,
                'result' => true,
                'success' => true,
            ],
            'facial' => [
                'data' => [
                    'matchProbability' => 1,
                    'errorMessage' => null,
                    'livenessProbability' => 0.99,
                    'isLive' => true,
                    'matched' => true,
                    'livenessScore' => 4.36,
                    'matchScore' => 92,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'realIdMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'expirationDateMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'heightMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlRestrictionsMatchDetails' => [
                        'similarityScore' => 99,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlClassMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                    ],
                    'isDlClassMatch' => true,
                    'isDobMatch' => true,
                    'isDocumentNumberMatch' => true,
                    'nameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isHeightMatch' => true,
                    'isExpirationDateMatch' => true,
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'weightMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'dlEndorsementMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 99,
                        'similarityThreshold' => 70,
                    ],
                    'isDlRestrictionsMatch' => true,
                    'isWeightMatch' => null,
                    'documentNumberMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'sexMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isEyeColorMatch' => true,
                    'isIssuerNameMatch' => true,
                    'isRealIdMatch' => true,
                    'isSexMatch' => true,
                    'isCountryCodeMatch' => null,
                    'isAddressMatch' => true,
                    'isIssueDateMatch' => true,
                    'isNationalityMatch' => null,
                    'eyeColorMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'addressMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'isDlEndorsementMatch' => true,
                    'isNameMatch' => true,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ipqs' => [
                'addressDetails' => [
                    'data' => [
                        'transaction_details' => [
                            'leaked_shipping_email' => null,
                            'valid_billing_address' => true,
                            'phone_name_identity_match' => 'Unknown',
                            'is_prepaid_card' => null,
                            'shipping_phone_carrier' => null,
                            'fraudulent_behavior' => false,
                            'billing_address_distance' => [
                                'kilometers' => 540,
                                'miles' => 336,
                            ],
                            'shipping_phone_country' => null,
                            'email_name_identity_match' => 'Unknown',
                            'phone_email_identity_match' => 'Unknown',
                            'shipping_phone_country_code' => null,
                            'phone_address_identity_match' => 'Unknown',
                            'valid_shipping_phone' => null,
                            'risky_username' => null,
                            'bin_country' => null,
                            'address_email_identity_match' => 'Unknown',
                            'shipping_phone_line_type' => 'Unknown',
                            'billing_phone_country' => null,
                            'billing_phone_country_code' => null,
                            'risky_shipping_phone' => null,
                            'billing_phone_line_type' => 'Unknown',
                            'name_address_identity_match' => 'Match',
                            'valid_billing_email' => null,
                            'leaked_user_data' => null,
                            'valid_shipping_address' => null,
                            'risk_factors' => [
                                'IP address is frequently associated with abusive behavior.',
                                'IP address recently engaged in suspicious behavior.',
                            ],
                            'user_activity' => null,
                            'bin_type' => 'N/A',
                            'shipping_address_distance' => [
                                'miles' => 336,
                                'kilometers' => 540,
                            ],
                            'valid_shipping_email' => null,
                            'billing_phone_carrier' => null,
                            'risk_score' => 89,
                            'bin_bank_name' => null,
                            'leaked_billing_email' => null,
                            'valid_billing_phone' => null,
                            'risky_billing_phone' => null,
                        ],
                        'bot_status' => false,
                        'frequent_abuser' => false,
                        'mobile' => false,
                        'active_tor' => false,
                        'success' => true,
                        'security_scanner' => false,
                        'recent_abuse' => false,
                        'ISP' => 'Cisco OpenDNS',
                        'longitude' => -90.08999634,
                        'active_vpn' => true,
                        'timezone' => 'America/Chicago',
                        'is_crawler' => false,
                        'country_code' => 'US',
                        'region' => 'Tennessee',
                        'high_risk_attacks' => false,
                        'dynamic_connection' => false,
                        'message' => 'Success',
                        'fraud_score' => 0,
                        'latitude' => 35.18999863,
                        'city' => 'Memphis',
                        'proxy_networks' => [
                            'Enterprise plan required to view active proxy networks.',
                        ],
                        'tor' => false,
                        'organization' => 'Cisco Secure Access',
                        'zip_code' => 'N/A',
                        'vpn' => true,
                        'host' => '155.190.17.5',
                        'shared_connection' => true,
                        'request_id' => 'Xwk8skZLDI',
                        'trusted_network' => true,
                        'connection_type' => 'Corporate',
                        'ASN' => 36692,
                        'abuse_velocity' => 'low',
                        'proxy' => true,
                    ],
                    'message' => null,
                    'result' => true,
                    'success' => true,
                ],
                'fraudDetails' => [
                    'data' => [
                        'first_seen' => '2025-06-10 14:55:10',
                        'longitude' => -90.09,
                        'organization' => 'Cisco Secure Access',
                        'tor' => false,
                        'is_crawler' => false,
                        'timezone' => 'America/Chicago',
                        'mobile' => true,
                        'bot_status' => false,
                        'connection_type' => 'Data Center',
                        'recent_abuse' => false,
                        'ip_address' => '155.190.17.5',
                        'browser' => 'Mobile Safari 18.5',
                        'proxy' => true,
                        'region' => 'Tennessee',
                        'active_tor' => false,
                        'device_id' => 'af2bfff29fef3b2ca8e2f18adadd5f5367294a6de5f6699b051cbe8318949964',
                        'isp' => 'Cisco OpenDNS',
                        'model' => 'iPhone',
                        'brand' => 'Apple',
                        'city' => 'Memphis',
                        'operating_system' => 'iOS 18.5',
                        'last_seen' => '2025-06-10 14:55:10',
                        'active_vpn' => true,
                        'fraud_chance' => 43,
                        'vpn' => true,
                        'latitude' => 35.19,
                        'request_id' => 'Xwk1YIDjbD',
                        'country' => 'US',
                        'reasons' => [
                            'VPN connection or anonymizer detected',
                            'User has an abnormal connection',
                            'Abnormal browser settings detected',
                        ],
                        'unique' => true,
                    ],
                    'success' => true,
                    'message' => null,
                    'result' => true,
                ],
            ],
            'OCR' => [
                'data' => [
                    'firstName' => 'John',
                    'issuerName' => 'Tennessee',
                    'countryCode' => 'USA',
                    'eyeColor' => 'Blue',
                    'dateOfIssueFormatted' => '11/11/2024',
                    'documentRecognized' => 1,
                    'dateOfBirthFormatted' => '11/02/1981',
                    'dateOfExpiry' => '2032-11-11',
                    'documentNumber' => '000000000',
                    'dlEndorsement' => 'NONE',
                    'dlRestrictions' => 'NONE',
                    'faceImageBase64' => null,
                    'fullName' => 'John Alan Testington',
                    'dateOfExpiryFormatted' => '11/11/2032',
                    'height' => '178 cm',
                    'dlClass' => 'DM',
                    'fullDocumentImageBase64' => null,
                    'address' => '1144 Belle Pond Ave, Knoxville, TN 37932-2288',
                    'age' => '43',
                    'lastName' => 'Testington',
                    'dateOfIssue' => '2024-11-11',
                    'weightKilograms' => null,
                    'dateOfBirth' => '1981-11-02',
                    'sex' => 'M',
                    'isRealID' => 'yes',
                    'errorMessage' => null,
                    'placeOfBirth' => null,
                    'nationality' => null,
                ],
                'message' => null,
                'success' => true,
                'imageQualityFindings' => [],
                'result' => true,
            ],
            'ip' => '172.19.0.34',
            'is_showroom' => true,
        ];
    }

    public function idVerificationFlagTestA(): array
    {
        return [
            'idcheck' => [
                'data' => [
                    'dLIDNumberRaw' => '000000000',
                    'heightFeetInches' => "5' 10\"",
                    'extendedResultCode' => 'Y',
                    'driverClass' => 'DM',
                    'endorsements' => null,
                    'expirationDate' => '11/11/2032',
                    'docCategory' => 'DL',
                    'city' => 'Knoxville',
                    'postalCode' => '37932-2288',
                    'issueDate' => '11/11/2024',
                    'duplicateDate' => null,
                    'mediaType' => '2D',
                    'uniqueID' => 6211,
                    'expired' => 'No',
                    'docType' => null,
                    'dateOfBirth' => '1981-11-02',
                    'lastName' => 'Testington',
                    'middleName' => 'Alan',
                    'weightKilograms' => null,
                    'restrictions' => null,
                    'gender' => 'Male',
                    'weightPounds' => null,
                    'isDuplicate' => 'No',
                    'organDonor' => 'Yes',
                    'age' => 43,
                    'socialSecurity' => null,
                    'state' => 'TN',
                    'processResult' => 'DocumentProcessOK',
                    'stateIssuerMismatch' => 'No',
                    'issuingJurisdictionAbbrv' => 'TN',
                    'hairColor' => null,
                    'dLIDNumberFormatted' => '000000000',
                    'transactionIdentifier' => '2cbb2fb1-b57f-4b8a-974c-09957866acd5',
                    'issuingJurisdictionCvt' => 'Tennessee',
                    'address2' => null,
                    'firstName' => 'John',
                    'testCard' => false,
                    'eyeColor' => 'Blue',
                    'isRealID' => 'Yes',
                    'heightCentimeters' => '178',
                    'address1' => '1144 Belle Pond Ave',
                ],
                'message' => null,
                'result' => true,
                'success' => true,
            ],
            'facial' => [
                'data' => [
                    'matchProbability' => 1,
                    'errorMessage' => null,
                    'livenessProbability' => 0.99,
                    'isLive' => true,
                    'matched' => true,
                    'livenessScore' => 4.36,
                    'matchScore' => 92,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'realIdMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'expirationDateMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'heightMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlRestrictionsMatchDetails' => [
                        'similarityScore' => 99,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlClassMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                    ],
                    'isDlClassMatch' => true,
                    'isDobMatch' => true,
                    'isDocumentNumberMatch' => true,
                    'nameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isHeightMatch' => true,
                    'isExpirationDateMatch' => true,
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'weightMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'dlEndorsementMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 99,
                        'similarityThreshold' => 70,
                    ],
                    'isDlRestrictionsMatch' => true,
                    'isWeightMatch' => null,
                    'documentNumberMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'sexMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isEyeColorMatch' => true,
                    'isIssuerNameMatch' => true,
                    'isRealIdMatch' => true,
                    'isSexMatch' => true,
                    'isCountryCodeMatch' => null,
                    'isAddressMatch' => true,
                    'isIssueDateMatch' => true,
                    'isNationalityMatch' => null,
                    'eyeColorMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'addressMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'isDlEndorsementMatch' => true,
                    'isNameMatch' => true,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ipqs' => [
                'addressDetails' => [
                    'data' => [
                        'transaction_details' => [
                            'leaked_shipping_email' => null,
                            'valid_billing_address' => true,
                            'phone_name_identity_match' => 'Unknown',
                            'is_prepaid_card' => null,
                            'shipping_phone_carrier' => null,
                            'fraudulent_behavior' => false,
                            'billing_address_distance' => [
                                'kilometers' => 540,
                                'miles' => 336,
                            ],
                            'shipping_phone_country' => null,
                            'email_name_identity_match' => 'Unknown',
                            'phone_email_identity_match' => 'Unknown',
                            'shipping_phone_country_code' => null,
                            'phone_address_identity_match' => 'Unknown',
                            'valid_shipping_phone' => null,
                            'risky_username' => null,
                            'bin_country' => null,
                            'address_email_identity_match' => 'Unknown',
                            'shipping_phone_line_type' => 'Unknown',
                            'billing_phone_country' => null,
                            'billing_phone_country_code' => null,
                            'risky_shipping_phone' => null,
                            'billing_phone_line_type' => 'Unknown',
                            'name_address_identity_match' => 'Match',
                            'valid_billing_email' => null,
                            'leaked_user_data' => null,
                            'valid_shipping_address' => null,
                            'risk_factors' => [
                                'IP address is frequently associated with abusive behavior.',
                                'IP address recently engaged in suspicious behavior.',
                            ],
                            'user_activity' => null,
                            'bin_type' => 'N/A',
                            'shipping_address_distance' => [
                                'miles' => 336,
                                'kilometers' => 540,
                            ],
                            'valid_shipping_email' => null,
                            'billing_phone_carrier' => null,
                            'risk_score' => 89,
                            'bin_bank_name' => null,
                            'leaked_billing_email' => null,
                            'valid_billing_phone' => null,
                            'risky_billing_phone' => null,
                        ],
                        'bot_status' => false,
                        'frequent_abuser' => false,
                        'mobile' => false,
                        'active_tor' => false,
                        'success' => true,
                        'security_scanner' => false,
                        'recent_abuse' => false,
                        'ISP' => 'Cisco OpenDNS',
                        'longitude' => -90.08999634,
                        'active_vpn' => true,
                        'timezone' => 'America/Chicago',
                        'is_crawler' => false,
                        'country_code' => 'US',
                        'region' => 'Tennessee',
                        'high_risk_attacks' => false,
                        'dynamic_connection' => false,
                        'message' => 'Success',
                        'fraud_score' => 75,
                        'latitude' => 35.18999863,
                        'city' => 'Memphis',
                        'proxy_networks' => [
                            'Enterprise plan required to view active proxy networks.',
                        ],
                        'tor' => false,
                        'organization' => 'Cisco Secure Access',
                        'zip_code' => 'N/A',
                        'vpn' => true,
                        'host' => '155.190.17.5',
                        'shared_connection' => true,
                        'request_id' => 'Xwk8skZLDI',
                        'trusted_network' => true,
                        'connection_type' => 'Corporate',
                        'ASN' => 36692,
                        'abuse_velocity' => 'low',
                        'proxy' => true,
                    ],
                    'message' => null,
                    'result' => true,
                    'success' => true,
                ],
                'fraudDetails' => [
                    'data' => [
                        'first_seen' => '2025-06-10 14:55:10',
                        'longitude' => -90.09,
                        'organization' => 'Cisco Secure Access',
                        'tor' => false,
                        'is_crawler' => false,
                        'timezone' => 'America/Chicago',
                        'mobile' => true,
                        'bot_status' => false,
                        'connection_type' => 'Data Center',
                        'recent_abuse' => false,
                        'ip_address' => '155.190.17.5',
                        'browser' => 'Mobile Safari 18.5',
                        'proxy' => true,
                        'region' => 'Tennessee',
                        'active_tor' => false,
                        'device_id' => 'af2bfff29fef3b2ca8e2f18adadd5f5367294a6de5f6699b051cbe8318949964',
                        'isp' => 'Cisco OpenDNS',
                        'model' => 'iPhone',
                        'brand' => 'Apple',
                        'city' => 'Memphis',
                        'operating_system' => 'iOS 18.5',
                        'last_seen' => '2025-06-10 14:55:10',
                        'active_vpn' => true,
                        'fraud_chance' => 43,
                        'vpn' => true,
                        'latitude' => 35.19,
                        'request_id' => 'Xwk1YIDjbD',
                        'country' => 'US',
                        'reasons' => [
                            'VPN connection or anonymizer detected',
                            'User has an abnormal connection',
                            'Abnormal browser settings detected',
                        ],
                        'unique' => true,
                    ],
                    'success' => true,
                    'message' => null,
                    'result' => true,
                ],
            ],
            'OCR' => [
                'data' => [
                    'firstName' => 'John',
                    'issuerName' => 'Tennessee',
                    'countryCode' => 'USA',
                    'eyeColor' => 'Blue',
                    'dateOfIssueFormatted' => '11/11/2024',
                    'documentRecognized' => 1,
                    'dateOfBirthFormatted' => '11/02/1981',
                    'dateOfExpiry' => '2032-11-11',
                    'documentNumber' => '000000000',
                    'dlEndorsement' => 'NONE',
                    'dlRestrictions' => 'NONE',
                    'faceImageBase64' => null,
                    'fullName' => 'John Alan Testington',
                    'dateOfExpiryFormatted' => '11/11/2032',
                    'height' => '178 cm',
                    'dlClass' => 'DM',
                    'fullDocumentImageBase64' => null,
                    'address' => '1144 Belle Pond Ave, Knoxville, TN 37932-2288',
                    'age' => '43',
                    'lastName' => 'Testington',
                    'dateOfIssue' => '2024-11-11',
                    'weightKilograms' => null,
                    'dateOfBirth' => '1981-11-02',
                    'sex' => 'M',
                    'isRealID' => 'yes',
                    'errorMessage' => null,
                    'placeOfBirth' => null,
                    'nationality' => null,
                ],
                'message' => null,
                'success' => true,
                'imageQualityFindings' => [],
                'result' => true,
            ],
            'ip' => '172.19.0.34',
            'is_showroom' => true,
        ];
    }

    public function idVerificationFlagTestB(): array
    {
        return [
            'idcheck' => [
                'data' => [
                    'dLIDNumberRaw' => '000000000',
                    'heightFeetInches' => "5' 10\"",
                    'extendedResultCode' => 'Y',
                    'driverClass' => 'DM',
                    'endorsements' => null,
                    'expirationDate' => '11/11/2032',
                    'docCategory' => 'DL',
                    'city' => 'Knoxville',
                    'postalCode' => '37932-2288',
                    'issueDate' => '11/11/2024',
                    'duplicateDate' => null,
                    'mediaType' => '2D',
                    'uniqueID' => 6211,
                    'expired' => 'No',
                    'docType' => null,
                    'dateOfBirth' => '1981-11-02',
                    'lastName' => 'Testington',
                    'middleName' => 'Alan',
                    'weightKilograms' => null,
                    'restrictions' => null,
                    'gender' => 'Male',
                    'weightPounds' => null,
                    'isDuplicate' => 'No',
                    'organDonor' => 'Yes',
                    'age' => 43,
                    'socialSecurity' => null,
                    'state' => 'TN',
                    'processResult' => 'DocumentProcessOK',
                    'stateIssuerMismatch' => 'No',
                    'issuingJurisdictionAbbrv' => 'TN',
                    'hairColor' => null,
                    'dLIDNumberFormatted' => '000000000',
                    'transactionIdentifier' => '2cbb2fb1-b57f-4b8a-974c-09957866acd5',
                    'issuingJurisdictionCvt' => 'Tennessee',
                    'address2' => null,
                    'firstName' => 'John',
                    'testCard' => false,
                    'eyeColor' => 'Blue',
                    'isRealID' => 'Yes',
                    'heightCentimeters' => '178',
                    'address1' => '1144 Belle Pond Ave',
                ],
                'message' => null,
                'result' => true,
                'success' => true,
            ],
            'facial' => [
                'data' => [
                    'matchProbability' => 1,
                    'errorMessage' => null,
                    'livenessProbability' => 0.99,
                    'isLive' => true,
                    'matched' => true,
                    'livenessScore' => 4.36,
                    'matchScore' => 92,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'realIdMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'expirationDateMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'heightMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlRestrictionsMatchDetails' => [
                        'similarityScore' => 99,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlClassMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                    ],
                    'isDlClassMatch' => true,
                    'isDobMatch' => true,
                    'isDocumentNumberMatch' => true,
                    'nameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isHeightMatch' => true,
                    'isExpirationDateMatch' => true,
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'weightMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'dlEndorsementMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 99,
                        'similarityThreshold' => 70,
                    ],
                    'isDlRestrictionsMatch' => true,
                    'isWeightMatch' => null,
                    'documentNumberMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'sexMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isEyeColorMatch' => true,
                    'isIssuerNameMatch' => true,
                    'isRealIdMatch' => true,
                    'isSexMatch' => true,
                    'isCountryCodeMatch' => null,
                    'isAddressMatch' => true,
                    'isIssueDateMatch' => true,
                    'isNationalityMatch' => null,
                    'eyeColorMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'addressMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'isDlEndorsementMatch' => true,
                    'isNameMatch' => true,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ipqs' => [
                'addressDetails' => [
                    'data' => [
                        'transaction_details' => [
                            'leaked_shipping_email' => null,
                            'valid_billing_address' => true,
                            'phone_name_identity_match' => 'Unknown',
                            'is_prepaid_card' => null,
                            'shipping_phone_carrier' => null,
                            'fraudulent_behavior' => false,
                            'billing_address_distance' => [
                                'kilometers' => 540,
                                'miles' => 336,
                            ],
                            'shipping_phone_country' => null,
                            'email_name_identity_match' => 'Unknown',
                            'phone_email_identity_match' => 'Unknown',
                            'shipping_phone_country_code' => null,
                            'phone_address_identity_match' => 'Unknown',
                            'valid_shipping_phone' => null,
                            'risky_username' => null,
                            'bin_country' => null,
                            'address_email_identity_match' => 'Unknown',
                            'shipping_phone_line_type' => 'Unknown',
                            'billing_phone_country' => null,
                            'billing_phone_country_code' => null,
                            'risky_shipping_phone' => null,
                            'billing_phone_line_type' => 'Unknown',
                            'name_address_identity_match' => 'Match',
                            'valid_billing_email' => null,
                            'leaked_user_data' => null,
                            'valid_shipping_address' => null,
                            'risk_factors' => [
                                'IP address is frequently associated with abusive behavior.',
                                'IP address recently engaged in suspicious behavior.',
                            ],
                            'user_activity' => null,
                            'bin_type' => 'N/A',
                            'shipping_address_distance' => [
                                'miles' => 336,
                                'kilometers' => 540,
                            ],
                            'valid_shipping_email' => null,
                            'billing_phone_carrier' => null,
                            'risk_score' => 89,
                            'bin_bank_name' => null,
                            'leaked_billing_email' => null,
                            'valid_billing_phone' => null,
                            'risky_billing_phone' => null,
                        ],
                        'bot_status' => false,
                        'frequent_abuser' => false,
                        'mobile' => false,
                        'active_tor' => false,
                        'success' => true,
                        'security_scanner' => false,
                        'recent_abuse' => false,
                        'ISP' => 'Cisco OpenDNS',
                        'longitude' => -90.08999634,
                        'active_vpn' => true,
                        'timezone' => 'America/Chicago',
                        'is_crawler' => false,
                        'country_code' => 'US',
                        'region' => 'Tennessee',
                        'high_risk_attacks' => false,
                        'dynamic_connection' => false,
                        'message' => 'Success',
                        'fraud_score' => 70,
                        'latitude' => 35.18999863,
                        'city' => 'Memphis',
                        'proxy_networks' => [
                            'Enterprise plan required to view active proxy networks.',
                        ],
                        'tor' => false,
                        'organization' => 'Cisco Secure Access',
                        'zip_code' => 'N/A',
                        'vpn' => true,
                        'host' => '155.190.17.5',
                        'shared_connection' => true,
                        'request_id' => 'Xwk8skZLDI',
                        'trusted_network' => true,
                        'connection_type' => 'Corporate',
                        'ASN' => 36692,
                        'abuse_velocity' => 'low',
                        'proxy' => true,
                    ],
                    'message' => null,
                    'result' => true,
                    'success' => true,
                ],
                'fraudDetails' => [
                    'data' => [
                        'first_seen' => '2025-06-10 14:55:10',
                        'longitude' => -90.09,
                        'organization' => 'Cisco Secure Access',
                        'tor' => false,
                        'is_crawler' => false,
                        'timezone' => 'America/Chicago',
                        'mobile' => true,
                        'bot_status' => false,
                        'connection_type' => 'Data Center',
                        'recent_abuse' => true,
                        'ip_address' => '155.190.17.5',
                        'browser' => 'Mobile Safari 18.5',
                        'proxy' => true,
                        'region' => 'Tennessee',
                        'active_tor' => false,
                        'device_id' => 'af2bfff29fef3b2ca8e2f18adadd5f5367294a6de5f6699b051cbe8318949964',
                        'isp' => 'Cisco OpenDNS',
                        'model' => 'iPhone',
                        'brand' => 'Apple',
                        'city' => 'Memphis',
                        'operating_system' => 'iOS 18.5',
                        'last_seen' => '2025-06-10 14:55:10',
                        'active_vpn' => true,
                        'fraud_chance' => 43,
                        'vpn' => true,
                        'latitude' => 35.19,
                        'request_id' => 'Xwk1YIDjbD',
                        'country' => 'US',
                        'reasons' => [
                            'VPN connection or anonymizer detected',
                            'User has an abnormal connection',
                            'Abnormal browser settings detected',
                        ],
                        'unique' => true,
                    ],
                    'success' => true,
                    'message' => null,
                    'result' => true,
                ],
            ],
            'OCR' => [
                'data' => [
                    'firstName' => 'John',
                    'issuerName' => 'Tennessee',
                    'countryCode' => 'USA',
                    'eyeColor' => 'Blue',
                    'dateOfIssueFormatted' => '11/11/2024',
                    'documentRecognized' => 1,
                    'dateOfBirthFormatted' => '11/02/1981',
                    'dateOfExpiry' => '2032-11-11',
                    'documentNumber' => '000000000',
                    'dlEndorsement' => 'NONE',
                    'dlRestrictions' => 'NONE',
                    'faceImageBase64' => null,
                    'fullName' => 'John Alan Testington',
                    'dateOfExpiryFormatted' => '11/11/2032',
                    'height' => '178 cm',
                    'dlClass' => 'DM',
                    'fullDocumentImageBase64' => null,
                    'address' => '1144 Belle Pond Ave, Knoxville, TN 37932-2288',
                    'age' => '43',
                    'lastName' => 'Testington',
                    'dateOfIssue' => '2024-11-11',
                    'weightKilograms' => null,
                    'dateOfBirth' => '1981-11-02',
                    'sex' => 'M',
                    'isRealID' => 'yes',
                    'errorMessage' => null,
                    'placeOfBirth' => null,
                    'nationality' => null,
                ],
                'message' => null,
                'success' => true,
                'imageQualityFindings' => [],
                'result' => true,
            ],
            'ip' => '172.19.0.34',
            'is_showroom' => true,
        ];
    }

    public function idVerificationFlagTestD(): array
    {
        return [
            'idcheck' => [
                'data' => [
                    'dLIDNumberRaw' => '000000000',
                    'heightFeetInches' => "5' 10\"",
                    'extendedResultCode' => 'Y',
                    'driverClass' => 'DM',
                    'endorsements' => null,
                    'expirationDate' => '11/11/2032',
                    'docCategory' => 'DL',
                    'city' => 'Knoxville',
                    'postalCode' => '37932-2288',
                    'issueDate' => '11/11/2024',
                    'duplicateDate' => null,
                    'mediaType' => '2D',
                    'uniqueID' => 6211,
                    'expired' => 'No',
                    'docType' => null,
                    'dateOfBirth' => '1981-11-02',
                    'lastName' => 'Testington',
                    'middleName' => 'Alan',
                    'weightKilograms' => null,
                    'restrictions' => null,
                    'gender' => 'Male',
                    'weightPounds' => null,
                    'isDuplicate' => 'No',
                    'organDonor' => 'Yes',
                    'age' => 43,
                    'socialSecurity' => null,
                    'state' => 'TN',
                    'processResult' => 'DocumentProcessOK',
                    'stateIssuerMismatch' => 'No',
                    'issuingJurisdictionAbbrv' => 'TN',
                    'hairColor' => null,
                    'dLIDNumberFormatted' => '000000000',
                    'transactionIdentifier' => '2cbb2fb1-b57f-4b8a-974c-09957866acd5',
                    'issuingJurisdictionCvt' => 'Tennessee',
                    'address2' => null,
                    'firstName' => 'John',
                    'testCard' => false,
                    'eyeColor' => 'Blue',
                    'isRealID' => 'Yes',
                    'heightCentimeters' => '178',
                    'address1' => '1144 Belle Pond Ave',
                ],
                'message' => null,
                'result' => true,
                'success' => true,
            ],
            'facial' => [
                'data' => [
                    'matchProbability' => 1,
                    'errorMessage' => null,
                    'livenessProbability' => 0.99,
                    'isLive' => true,
                    'matched' => true,
                    'livenessScore' => 4.36,
                    'matchScore' => 92,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'realIdMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'expirationDateMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'heightMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlRestrictionsMatchDetails' => [
                        'similarityScore' => 99,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlClassMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                    ],
                    'isDlClassMatch' => true,
                    'isDobMatch' => true,
                    'isDocumentNumberMatch' => true,
                    'nameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isHeightMatch' => true,
                    'isExpirationDateMatch' => true,
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'weightMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'dlEndorsementMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 99,
                        'similarityThreshold' => 70,
                    ],
                    'isDlRestrictionsMatch' => true,
                    'isWeightMatch' => null,
                    'documentNumberMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'sexMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isEyeColorMatch' => true,
                    'isIssuerNameMatch' => true,
                    'isRealIdMatch' => true,
                    'isSexMatch' => true,
                    'isCountryCodeMatch' => null,
                    'isAddressMatch' => true,
                    'isIssueDateMatch' => true,
                    'isNationalityMatch' => null,
                    'eyeColorMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'addressMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'isDlEndorsementMatch' => true,
                    'isNameMatch' => true,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ipqs' => [
                'addressDetails' => [
                    'data' => [
                        'transaction_details' => [
                            'leaked_shipping_email' => null,
                            'valid_billing_address' => true,
                            'phone_name_identity_match' => 'Unknown',
                            'is_prepaid_card' => null,
                            'shipping_phone_carrier' => null,
                            'fraudulent_behavior' => false,
                            'billing_address_distance' => [
                                'kilometers' => 540,
                                'miles' => 336,
                            ],
                            'shipping_phone_country' => null,
                            'email_name_identity_match' => 'Unknown',
                            'phone_email_identity_match' => 'Unknown',
                            'shipping_phone_country_code' => null,
                            'phone_address_identity_match' => 'Unknown',
                            'valid_shipping_phone' => null,
                            'risky_username' => null,
                            'bin_country' => null,
                            'address_email_identity_match' => 'Unknown',
                            'shipping_phone_line_type' => 'Unknown',
                            'billing_phone_country' => null,
                            'billing_phone_country_code' => null,
                            'risky_shipping_phone' => null,
                            'billing_phone_line_type' => 'Unknown',
                            'name_address_identity_match' => 'Match',
                            'valid_billing_email' => null,
                            'leaked_user_data' => null,
                            'valid_shipping_address' => null,
                            'risk_factors' => [
                                'IP address is frequently associated with abusive behavior.',
                                'IP address recently engaged in suspicious behavior.',
                            ],
                            'user_activity' => null,
                            'bin_type' => 'N/A',
                            'shipping_address_distance' => [
                                'miles' => 336,
                                'kilometers' => 540,
                            ],
                            'valid_shipping_email' => null,
                            'billing_phone_carrier' => null,
                            'risk_score' => 89,
                            'bin_bank_name' => null,
                            'leaked_billing_email' => null,
                            'valid_billing_phone' => null,
                            'risky_billing_phone' => null,
                        ],
                        'bot_status' => false,
                        'frequent_abuser' => false,
                        'mobile' => false,
                        'active_tor' => false,
                        'success' => true,
                        'security_scanner' => false,
                        'recent_abuse' => false,
                        'ISP' => 'Cisco OpenDNS',
                        'longitude' => -90.08999634,
                        'active_vpn' => true,
                        'timezone' => 'America/Chicago',
                        'is_crawler' => false,
                        'country_code' => 'US',
                        'region' => 'Tennessee',
                        'high_risk_attacks' => false,
                        'dynamic_connection' => false,
                        'message' => 'Success',
                        'fraud_score' => 0,
                        'latitude' => 35.18999863,
                        'city' => 'Memphis',
                        'proxy_networks' => [
                            'Enterprise plan required to view active proxy networks.',
                        ],
                        'tor' => false,
                        'organization' => 'Cisco Secure Access',
                        'zip_code' => 'N/A',
                        'vpn' => true,
                        'host' => '155.190.17.5',
                        'shared_connection' => true,
                        'request_id' => 'Xwk8skZLDI',
                        'trusted_network' => true,
                        'connection_type' => 'Corporate',
                        'ASN' => 36692,
                        'abuse_velocity' => 'low',
                        'proxy' => true,
                    ],
                    'message' => null,
                    'result' => true,
                    'success' => true,
                ],
                'fraudDetails' => [
                    'data' => [
                        'first_seen' => '2025-06-10 14:55:10',
                        'longitude' => -90.09,
                        'organization' => 'Cisco Secure Access',
                        'tor' => false,
                        'is_crawler' => false,
                        'timezone' => 'America/Chicago',
                        'mobile' => true,
                        'bot_status' => false,
                        'connection_type' => 'Data Center',
                        'recent_abuse' => false,
                        'ip_address' => '155.190.17.5',
                        'browser' => 'Mobile Safari 18.5',
                        'proxy' => true,
                        'region' => 'Tennessee',
                        'active_tor' => false,
                        'device_id' => 'af2bfff29fef3b2ca8e2f18adadd5f5367294a6de5f6699b051cbe8318949964',
                        'isp' => 'Cisco OpenDNS',
                        'model' => 'iPhone',
                        'brand' => 'Apple',
                        'city' => 'Memphis',
                        'operating_system' => 'iOS 18.5',
                        'last_seen' => '2025-06-10 14:55:10',
                        'active_vpn' => true,
                        'fraud_chance' => 75,
                        'vpn' => true,
                        'latitude' => 35.19,
                        'request_id' => 'Xwk1YIDjbD',
                        'country' => 'US',
                        'reasons' => [
                            'VPN connection or anonymizer detected',
                            'User has an abnormal connection',
                            'Abnormal browser settings detected',
                        ],
                        'unique' => true,
                    ],
                    'success' => true,
                    'message' => null,
                    'result' => true,
                ],
            ],
            'OCR' => [
                'data' => [
                    'firstName' => 'John',
                    'issuerName' => 'Tennessee',
                    'countryCode' => 'USA',
                    'eyeColor' => 'Blue',
                    'dateOfIssueFormatted' => '11/11/2024',
                    'documentRecognized' => 1,
                    'dateOfBirthFormatted' => '11/02/1981',
                    'dateOfExpiry' => '2032-11-11',
                    'documentNumber' => '000000000',
                    'dlEndorsement' => 'NONE',
                    'dlRestrictions' => 'NONE',
                    'faceImageBase64' => null,
                    'fullName' => 'John Alan Testington',
                    'dateOfExpiryFormatted' => '11/11/2032',
                    'height' => '178 cm',
                    'dlClass' => 'DM',
                    'fullDocumentImageBase64' => null,
                    'address' => '1144 Belle Pond Ave, Knoxville, TN 37932-2288',
                    'age' => '43',
                    'lastName' => 'Testington',
                    'dateOfIssue' => '2024-11-11',
                    'weightKilograms' => null,
                    'dateOfBirth' => '1981-11-02',
                    'sex' => 'M',
                    'isRealID' => 'yes',
                    'errorMessage' => null,
                    'placeOfBirth' => null,
                    'nationality' => null,
                ],
                'message' => null,
                'success' => true,
                'imageQualityFindings' => [],
                'result' => true,
            ],
            'ip' => '172.19.0.34',
            'is_showroom' => true,
        ];
    }

    public function idVerificationFlagC(): array
    {
        return [
            'idcheck' => [
                'data' => [
                    'dLIDNumberRaw' => '000000000',
                    'heightFeetInches' => "5' 10\"",
                    'extendedResultCode' => 'Y',
                    'driverClass' => 'DM',
                    'endorsements' => null,
                    'expirationDate' => '11/11/2032',
                    'docCategory' => 'DL',
                    'city' => 'Knoxville',
                    'postalCode' => '37932-2288',
                    'issueDate' => '11/11/2024',
                    'duplicateDate' => null,
                    'mediaType' => '2D',
                    'uniqueID' => 6211,
                    'expired' => 'No',
                    'docType' => null,
                    'dateOfBirth' => '1981-11-02',
                    'lastName' => 'Testington',
                    'middleName' => 'Alan',
                    'weightKilograms' => null,
                    'restrictions' => null,
                    'gender' => 'Male',
                    'weightPounds' => null,
                    'isDuplicate' => 'No',
                    'organDonor' => 'Yes',
                    'age' => 43,
                    'socialSecurity' => null,
                    'state' => 'TN',
                    'processResult' => 'DocumentProcessOK',
                    'stateIssuerMismatch' => 'No',
                    'issuingJurisdictionAbbrv' => 'TN',
                    'hairColor' => null,
                    'dLIDNumberFormatted' => '000000000',
                    'transactionIdentifier' => '2cbb2fb1-b57f-4b8a-974c-09957866acd5',
                    'issuingJurisdictionCvt' => 'Tennessee',
                    'address2' => null,
                    'firstName' => 'John',
                    'testCard' => false,
                    'eyeColor' => 'Blue',
                    'isRealID' => 'Yes',
                    'heightCentimeters' => '178',
                    'address1' => '1144 Belle Pond Ave',
                ],
                'message' => null,
                'result' => true,
                'success' => true,
            ],
            'facial' => [
                'data' => [
                    'matchProbability' => 1,
                    'errorMessage' => null,
                    'livenessProbability' => 0.99,
                    'isLive' => true,
                    'matched' => true,
                    'livenessScore' => 4.36,
                    'matchScore' => 92,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ocr_match' => [
                'data' => [
                    'realIdMatchDetails' => [
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                    ],
                    'issueDateMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'dobMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'expirationDateMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'heightMatchDetails' => [
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlRestrictionsMatchDetails' => [
                        'similarityScore' => 99,
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityThreshold' => 70,
                    ],
                    'dlClassMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                    ],
                    'isDlClassMatch' => true,
                    'isDobMatch' => true,
                    'isDocumentNumberMatch' => true,
                    'nameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isHeightMatch' => true,
                    'isExpirationDateMatch' => true,
                    'issuerNameMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'weightMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => null,
                        'details' => 'Missing value for comparison',
                    ],
                    'dlEndorsementMatchDetails' => [
                        'details' => 'Considered match with slight discrepancy in either barcode and/or front data',
                        'similarityScore' => 99,
                        'similarityThreshold' => 70,
                    ],
                    'isDlRestrictionsMatch' => true,
                    'isWeightMatch' => null,
                    'documentNumberMatchDetails' => [
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'sexMatchDetails' => [
                        'similarityScore' => 100,
                        'similarityThreshold' => 70,
                        'details' => 'Exact match between barcode and front data',
                    ],
                    'isEyeColorMatch' => true,
                    'isIssuerNameMatch' => true,
                    'isRealIdMatch' => true,
                    'isSexMatch' => true,
                    'isCountryCodeMatch' => null,
                    'isAddressMatch' => true,
                    'isIssueDateMatch' => true,
                    'isNationalityMatch' => null,
                    'eyeColorMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'addressMatchDetails' => [
                        'details' => 'Exact match between barcode and front data',
                        'similarityThreshold' => 70,
                        'similarityScore' => 100,
                    ],
                    'isDlEndorsementMatch' => true,
                    'isNameMatch' => true,
                ],
                'success' => true,
                'message' => null,
                'result' => true,
            ],
            'ipqs' => [
                'addressDetails' => [
                    'data' => [
                        'transaction_details' => [
                            'leaked_shipping_email' => null,
                            'valid_billing_address' => true,
                            'phone_name_identity_match' => 'Unknown',
                            'is_prepaid_card' => null,
                            'shipping_phone_carrier' => null,
                            'fraudulent_behavior' => false,
                            'billing_address_distance' => [
                                'kilometers' => 540,
                                'miles' => 336,
                            ],
                            'shipping_phone_country' => null,
                            'email_name_identity_match' => 'Unknown',
                            'phone_email_identity_match' => 'Unknown',
                            'shipping_phone_country_code' => null,
                            'phone_address_identity_match' => 'Unknown',
                            'valid_shipping_phone' => null,
                            'risky_username' => null,
                            'bin_country' => null,
                            'address_email_identity_match' => 'Unknown',
                            'shipping_phone_line_type' => 'Unknown',
                            'billing_phone_country' => null,
                            'billing_phone_country_code' => null,
                            'risky_shipping_phone' => null,
                            'billing_phone_line_type' => 'Unknown',
                            'name_address_identity_match' => 'Match',
                            'valid_billing_email' => null,
                            'leaked_user_data' => null,
                            'valid_shipping_address' => null,
                            'risk_factors' => [
                                'IP address is frequently associated with abusive behavior.',
                                'IP address recently engaged in suspicious behavior.',
                            ],
                            'user_activity' => null,
                            'bin_type' => 'N/A',
                            'shipping_address_distance' => [
                                'miles' => 336,
                                'kilometers' => 540,
                            ],
                            'valid_shipping_email' => null,
                            'billing_phone_carrier' => null,
                            'risk_score' => 89,
                            'bin_bank_name' => null,
                            'leaked_billing_email' => null,
                            'valid_billing_phone' => null,
                            'risky_billing_phone' => null,
                        ],
                        'bot_status' => false,
                        'frequent_abuser' => false,
                        'mobile' => false,
                        'active_tor' => false,
                        'success' => true,
                        'security_scanner' => false,
                        'recent_abuse' => false,
                        'ISP' => 'Cisco OpenDNS',
                        'longitude' => -90.08999634,
                        'active_vpn' => true,
                        'timezone' => 'America/Chicago',
                        'is_crawler' => false,
                        'country_code' => 'US',
                        'region' => 'Tennessee',
                        'high_risk_attacks' => false,
                        'dynamic_connection' => false,
                        'message' => 'Success',
                        'fraud_score' => 70,
                        'latitude' => 35.18999863,
                        'city' => 'Memphis',
                        'proxy_networks' => [
                            'Enterprise plan required to view active proxy networks.',
                        ],
                        'tor' => false,
                        'organization' => 'Cisco Secure Access',
                        'zip_code' => 'N/A',
                        'vpn' => true,
                        'host' => '155.190.17.5',
                        'shared_connection' => true,
                        'request_id' => 'Xwk8skZLDI',
                        'trusted_network' => true,
                        'connection_type' => 'Corporate',
                        'ASN' => 36692,
                        'abuse_velocity' => 'low',
                        'proxy' => true,
                    ],
                    'message' => null,
                    'result' => true,
                    'success' => true,
                ],
                'fraudDetails' => [
                    'data' => [
                        'first_seen' => '2025-06-10 14:55:10',
                        'longitude' => -90.09,
                        'organization' => 'Cisco Secure Access',
                        'tor' => false,
                        'is_crawler' => false,
                        'timezone' => 'America/Chicago',
                        'mobile' => true,
                        'bot_status' => false,
                        'connection_type' => 'Data Center',
                        'recent_abuse' => true,
                        'ip_address' => '155.190.17.5',
                        'browser' => 'Mobile Safari 18.5',
                        'proxy' => true,
                        'region' => 'Tennessee',
                        'active_tor' => false,
                        'device_id' => 'af2bfff29fef3b2ca8e2f18adadd5f5367294a6de5f6699b051cbe8318949964',
                        'isp' => 'Cisco OpenDNS',
                        'model' => 'iPhone',
                        'brand' => 'Apple',
                        'city' => 'Memphis',
                        'operating_system' => 'iOS 18.5',
                        'last_seen' => '2025-06-10 14:55:10',
                        'active_vpn' => true,
                        'fraud_chance' => 43,
                        'vpn' => true,
                        'latitude' => 35.19,
                        'request_id' => 'Xwk1YIDjbD',
                        'country' => 'US',
                        'reasons' => [
                            'VPN connection or anonymizer detected',
                            'User has an abnormal connection',
                            'Abnormal browser settings detected',
                        ],
                        'unique' => true,
                    ],
                    'success' => true,
                    'message' => null,
                    'result' => true,
                ],
            ],
            'OCR' => [
                'data' => [
                    'firstName' => 'John',
                    'issuerName' => 'Tennessee',
                    'countryCode' => 'USA',
                    'eyeColor' => 'Blue',
                    'dateOfIssueFormatted' => '11/11/2024',
                    'documentRecognized' => 1,
                    'dateOfBirthFormatted' => '11/02/1981',
                    'dateOfExpiry' => '2032-11-11',
                    'documentNumber' => '000000000',
                    'dlEndorsement' => 'NONE',
                    'dlRestrictions' => 'NONE',
                    'faceImageBase64' => null,
                    'fullName' => 'John Alan Testington',
                    'dateOfExpiryFormatted' => '11/11/2032',
                    'height' => '178 cm',
                    'dlClass' => 'DM',
                    'fullDocumentImageBase64' => null,
                    'address' => '1144 Belle Pond Ave, Knoxville, TN 37932-2288',
                    'age' => '43',
                    'lastName' => 'Testington',
                    'dateOfIssue' => '2024-11-11',
                    'weightKilograms' => null,
                    'dateOfBirth' => '1981-11-02',
                    'sex' => 'M',
                    'isRealID' => 'yes',
                    'errorMessage' => null,
                    'placeOfBirth' => null,
                    'nationality' => null,
                ],
                'message' => null,
                'success' => true,
                'imageQualityFindings' => [],
                'result' => true,
            ],
            'ip' => '172.19.0.34',
            'is_showroom' => true,
        ];
    }

    public function testIdVerificationShowroom()
    {
        $verificationData = $this->idVerificationData();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);

        $this->assertEquals('fail', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testIdVerificationShowroomWithFlag()
    {
        $verificationData = $this->idVerificationFlag();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);
        $this->assertEquals('green', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testIdVerificationCaseA()
    {
        $verificationData = $this->idVerificationFlagTestA();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);
        $this->assertEquals('flag', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testIdVerificationCaseB()
    {
        $verificationData = $this->idVerificationFlagTestB();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);
        $this->assertEquals('green', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testIdVerificationCaseC()
    {
        $verificationData = $this->idVerificationFlagC();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);
        $this->assertEquals('green', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testIdVerificationCaseD()
    {
        $verificationData = $this->idVerificationFlagTestD();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        // Get person name from lead entity
        $name = $lead->people->name;

        $verificationResults = IdVerificationService::processVerificationData($verificationData, $name, $isShowRoom);
        $this->assertEquals('flag', $verificationResults['status']);
        $this->assertArrayHasKey('flags', $verificationResults);
        $this->assertArrayHasKey('failures', $verificationResults);
        $this->assertArrayHasKey('results', $verificationResults);
        $this->assertArrayHasKey('message', $verificationResults);
        $this->assertArrayHasKey('ocMatch', $verificationResults);
        $this->assertArrayHasKey('status', $verificationResults);
    }

    public function testUpdatePeopleInfo()
    {
        $verificationData = $this->idVerificationData();

        $isShowRoom = $params['is_showroom'] ?? false;
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        $lead = Lead::factory()->withAppId($app->getId())->withCompanyId($company->getId())->create();

        $name = $lead->people->name;

        // Update people info
        PeopleService::updatePeopleInformation($lead->people, $verificationData);

        // Assert that the lead's people info has been updated
        $this->assertEquals('Keira Knightley', People::getById($lead->people->getId())->name);
    }
}
