<?php

declare(strict_types=1);

namespace Tests\Event\Integration;

use Kanvas\Apps\Models\Apps;
use Kanvas\Event\Events\Actions\CreateEventAction;
use Kanvas\Event\Events\DataTransferObject\Event as EventDTO;
use Kanvas\Event\Events\Models\Event as ModelsEvent;
use Kanvas\Event\Events\Models\EventCategory;
use Kanvas\Event\Events\Models\EventType;
use Kanvas\Event\Support\Setup;
use Tests\TestCase;

final class CreateEventActionSlugTest extends TestCase
{
    public function testSameNameWhileFirstIsLiveUpdatesInPlace(): void
    {
        [$app, $user, $company] = $this->bootstrapEventSetup();
        $name = 'Service Appointment ' . fake()->uuid();

        $first = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();

        $second = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();

        $this->assertSame($first->getId(), $second->getId(), 'Idempotent retry should update the same event');
        $this->assertSame($first->slug, $second->slug, 'Slug should not change for live duplicates');
    }

    public function testSoftDeletedCollisionGetsIncrementedSuffix(): void
    {
        [$app, $user, $company] = $this->bootstrapEventSetup();
        $name = 'Service Appointment ' . fake()->uuid();

        $first = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();
        $originalSlug = $first->slug;

        $first->delete();

        $second = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();

        $this->assertNotSame($first->getId(), $second->getId());
        $this->assertSame($originalSlug . '-1', $second->slug);
    }

    public function testMultipleSoftDeletedCollisionsIncrementCounter(): void
    {
        [$app, $user, $company] = $this->bootstrapEventSetup();
        $name = 'Service Appointment ' . fake()->uuid();

        $first = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();
        $originalSlug = $first->slug;
        $first->delete();

        $second = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();
        $this->assertSame($originalSlug . '-1', $second->slug);
        $second->delete();

        $third = new CreateEventAction($this->buildEventDto($app, $user, $company, $name))
            ->disableWorkflow()
            ->execute();
        $this->assertSame($originalSlug . '-2', $third->slug);

        $this->assertTrue(
            ModelsEvent::withTrashed()
                ->where('slug', $originalSlug)
                ->where('apps_id', $app->getId())
                ->where('companies_id', $company->getId())
                ->where('is_deleted', '!=', 0)
                ->exists(),
            'Original soft-deleted row should still be present'
        );
    }

    /**
     * @return array{0: Apps, 1: \Baka\Users\Contracts\UserInterface, 2: \Baka\Contracts\CompanyInterface}
     */
    private function bootstrapEventSetup(): array
    {
        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        new Setup($app, $user, $company)->run();

        return [$app, $user, $company];
    }

    private function buildEventDto($app, $user, $company, string $name): EventDTO
    {
        return EventDTO::fromMultiple($app, $user, $company, [
            'name' => $name,
            'description' => 'Generated by CreateEventActionSlugTest',
            'category_id' => EventCategory::fromApp($app)->fromCompany($company)->first()->getId(),
            'type_id' => EventType::fromApp($app)->fromCompany($company)->first()->getId(),
            'dates' => [],
        ]);
    }
}
