<?php

declare(strict_types=1);

namespace Tests\Event\Integration;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Notification;
use Kanvas\Apps\Models\Apps;
use Kanvas\Event\Events\Actions\CreateEventAction;
use Kanvas\Event\Events\DataTransferObject\Event as EventDTO;
use Kanvas\Event\Events\Models\EventCategory;
use Kanvas\Event\Events\Models\EventType;
use Kanvas\Event\Support\Setup;
use Kanvas\Guild\Customers\Enums\ContactTypeEnum;
use Tests\TestCase;

/**
 * The agent calendar tools book from a queue worker, where `auth()->user()` is null. A company's
 * first booking is the one that has to create its own ParticipantType and pass motive — the two
 * writes that reach `CompaniesIdTrait` if they are not handed a company outright.
 */
final class CreateEventActionWithoutAuthTest extends TestCase
{
    use DatabaseTransactions;

    protected function connectionsToTransact(): array
    {
        return [null, 'event', 'crm'];
    }

    public function testBooksForACompanyMissingItsTenantDefaultsWithoutAnAuthenticatedUser(): void
    {
        Notification::fake();

        $app = app(Apps::class);
        $user = auth()->user();
        $company = $user->getCurrentCompany();

        new Setup($app, $user, $company)->run();

        $start = Carbon::now()->addDays(3)->setTime(10, 0);
        $end = $start->copy()->addMinutes(30);

        $dto = EventDTO::fromMultiple($app, $user, $company, [
            'name' => 'Agent Booking ' . fake()->uuid(),
            'description' => 'Generated by CreateEventActionWithoutAuthTest',
            'category_id' => EventCategory::fromApp($app)->fromCompany($company)->first()->getId(),
            'type_id' => EventType::fromApp($app)->fromCompany($company)->first()->getId(),
            'participants' => [
                [
                    'firstname' => 'Ada',
                    'lastname' => 'Lovelace',
                    'contacts' => [
                        [
                            'contacts_types_id' => ContactTypeEnum::EMAIL->value,
                            'value' => 'agent-booking-' . uniqid() . '@example.com',
                        ],
                    ],
                ],
            ],
            'dates' => [
                [
                    'date' => $start->format('Y-m-d'),
                    'start_time' => $start->format('H:i'),
                    'end_time' => $end->format('H:i'),
                ],
            ],
            'start_at' => $start,
            'end_at' => $end,
        ]);

        $this->forgetTenantDefaults($app->getId(), $company->getId());

        // TokenGuard has no logout(); forgetUser() drops the acting user and there is no request
        // token in a console context for user() to re-resolve from — exactly the queue's situation.
        Auth::forgetUser();
        $this->assertNull(auth()->user());

        $event = new CreateEventAction($dto)->disableWorkflow()->execute();

        $this->assertTrue($event->exists);
        $this->assertSame($company->getId(), (int) $event->companies_id);

        $this->assertDatabaseHas('participant_types', [
            'name' => 'Attendee',
            'apps_id' => $app->getId(),
            'companies_id' => $company->getId(),
        ], 'event');

        $this->assertDatabaseHas('participant_pass_motives', [
            'name' => 'Default',
            'apps_id' => $app->getId(),
            'companies_id' => $company->getId(),
        ], 'event');

        $this->assertDatabaseHas('participant_passes', [
            'event_id' => $event->getId(),
            'apps_id' => $app->getId(),
            'companies_id' => $company->getId(),
        ], 'event');
    }

    /**
     * Hard-deleted rather than soft-deleted: the lookups these rows serve are `firstOrCreate`,
     * which would happily reuse a soft-deleted row and skip the insert this test is about.
     */
    private function forgetTenantDefaults(int $appId, int $companyId): void
    {
        foreach (['participant_types', 'participant_pass_motives'] as $table) {
            DB::connection('event')
                ->table($table)
                ->where('apps_id', $appId)
                ->where('companies_id', $companyId)
                ->delete();
        }
    }
}
