type AIAgentSession {
    name: String!
    user: Mixed!
    id: ID!
    company: Company!
    company_config: Mixed
    content: Mixed
    channel: String
}

extend type Query @guard {
    aiAgentSession(id: ID!): AIAgentSession!
        @field(
            resolver: "App\\GraphQL\\Intelligence\\Queries\\AgentSessionQuery@getSessionInfo"
        )

    testCreateFirstMessage(lead_id: ID!): Mixed
        @field(
            resolver: "App\\GraphQL\\Intelligence\\Queries\\TestCreateFirstMessageQuery@getData"
        )
}
