<?php

declare(strict_types=1);

namespace Kanvas\Connectors\NetSuite\Enums;

enum ConfigurationEnum: string
{
    case NET_SUITE_ACCOUNT_CONFIG = 'NET_SUITE_ACCOUNT_CONFIG';
    case NET_SUITE_CUSTOM_API_URL = 'NET_SUITE_CUSTOM_API_URL';
    case NET_SUITE_MINIMUM_PRODUCT_QUANTITY = 'NET_SUITE_SET_B2B_MINIMUM_PRODUCT_QUANTITY';
    case NET_SUITE_DEFAULT_WAREHOUSE = 'NET_SUITE_DEFAULT_WAREHOUSE';
    case NET_SUITE_USE_LEGACY_PRODUCT_SEARCH = 'NET_SUITE_USE_LEGACY_PRODUCT_SEARCH';
    case NET_SUITE_MAX_CONCURRENT_REQUESTS = 'NET_SUITE_MAX_CONCURRENT_REQUESTS';
    case NET_SUITE_QUOTE_PRODUCT_SAVED_SEARCH_ID = 'NET_SUITE_QUOTE_PRODUCT_SAVED_SEARCH_ID';
}
