<?php

declare(strict_types=1);

namespace Kanvas\Connectors\NetSuite\Enums;

enum CustomFieldEnum: string
{
    case NET_SUITE_CUSTOMER_ID = 'NET_SUITE_CUSTOMER_ID';
    case NET_SUITE_LOCATION_ID = 'NET_SUITE_LOCATION_ID';
    case NET_SUITE_MAP_PRICE_CUSTOM_FIELD = 'custitem40';
    case NET_SUITE_COLOR_CODE_CUSTOM_FIELD = 'custitem15';
    case NET_SUITE_QUOTE_ID = 'NET_SUITE_QUOTE_ID';
    case NET_SUITE_QUOTE_NUMBER = 'NET_SUITE_QUOTE_NUMBER';
    case NET_SUITE_QUOTE_STATUS = 'NET_SUITE_QUOTE_STATUS';
    case NET_SUITE_QUOTE_TOTAL = 'NET_SUITE_QUOTE_TOTAL';
    case NET_SUITE_SALES_ORDER_ID = 'NET_SUITE_SALES_ORDER_ID';
    case NET_SUITE_SALES_ORDER_NUMBER = 'NET_SUITE_SALES_ORDER_NUMBER';
    case NET_SUITE_PUSHED_AT = 'NET_SUITE_PUSHED_AT';
    case NET_SUITE_CONVERTED_AT = 'NET_SUITE_CONVERTED_AT';
    case NET_SUITE_LAST_SYNC = 'NET_SUITE_LAST_SYNC';
}
