<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Twilio\Enums;

enum ConfigurationEnum: string
{
    case TWILIO_ACCOUNT_SID = 'TWILIO_ACCOUNT_SID';
    case TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN';
    case TWILIO_VERIFICATION_SID = 'TWILIO_VERIFICATION_SID';
    case TWILIO_VERIFICATION_SKIP_USERS = 'TWILIO_VERIFICATION_SKIP_USERS';
    case TWILIO_2FA_SEND_RATE_LIMIT = 'TWILIO_2FA_SEND_RATE_LIMIT';
    case TWILIO_2FA_VERIFY_RATE_LIMIT = 'TWILIO_2FA_VERIFY_RATE_LIMIT';
    case TWILIO_2FA_SEND_RATE_LIMIT_DECAY = 'TWILIO_2FA_SEND_RATE_LIMIT_DECAY';
    case TWILIO_2FA_VERIFY_RATE_LIMIT_DECAY = 'TWILIO_2FA_VERIFY_RATE_LIMIT_DECAY';
    case TWILIO_2FA_SEND_COOLDOWN_SECONDS = 'TWILIO_2FA_SEND_COOLDOWN_SECONDS';
}

