<?php

declare(strict_types=1);

namespace Kanvas\Intelligence\AgentRuntime\DataTransferObject;

use Illuminate\Support\Carbon;
use Spatie\LaravelData\Attributes\DataCollectionOf;
use Spatie\LaravelData\Data;

/**
 * rawMeta is the catch-all for runtime-specific session fields we don't
 * have typed columns for — it lands in agent_conversations.meta as-is.
 */
final class ParsedSessionTranscript extends Data
{
    public function __construct(
        public readonly string $sessionId,
        // Auto-generated by Hermes when available; JSONL fallback synthesizes one.
        public readonly ?string $title,
        public readonly ?string $source,
        public readonly ?string $model,
        public readonly ?string $systemPrompt,
        public readonly ?string $parentSessionId,
        public readonly ?Carbon $startedAt,
        public readonly ?Carbon $endedAt,
        public readonly ?string $endReason,
        public readonly ?int $messageCount,
        public readonly ?int $toolCallCount,
        public readonly ?int $inputTokens,
        public readonly ?int $outputTokens,
        public readonly ?int $cacheReadTokens,
        public readonly ?int $cacheWriteTokens,
        public readonly ?int $reasoningTokens,
        public readonly ?float $estimatedCostUsd,
        public readonly ?float $actualCostUsd,
        public readonly ?string $handoffState,
        // 'state.db' or 'jsonl' — tags rows so a later state.db run can re-enrich jsonl-imported ones.
        public readonly string $sourceReader,
        /** @var list<ParsedMessage> */
        #[DataCollectionOf(ParsedMessage::class)]
        public readonly array $messages,
        /** @var array<string, mixed> */
        public readonly array $rawMeta = [],
    ) {
    }
}
