<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Recombee\Enums;

enum ConfigurationEnum: string
{
    case RECOMBEE_DATABASE = 'RECOMBEE_DATABASE';
    case RECOMBEE_API_KEY = 'RECOMBEE_API_KEY';
    case RECOMBEE_REGION = 'RECOMBEE_REGION';
    case RECOMBEE_ROTATION_RATE = 'RECOMBEE_ROTATION_RATE';
    case RECOMBEE_ROTATION_TIME = 'RECOMBEE_ROTATION_TIME';
    case FOLLOWS_ENGINE_RECOMBEE_DATABASE = 'FOLLOWS_ENGINE_RECOMBEE_DATABASE';
    case FOLLOWS_ENGINE_RECOMBEE_API_KEY = 'FOLLOWS_ENGINE_RECOMBEE_API_KEY';
    case FOLLOWS_ENGINE_RECOMBEE_REGION = 'FOLLOWS_ENGINE_RECOMBEE_REGION';
}
