<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Reynolds\Enums;

enum ConfigurationEnum: string
{
    case REYNOLDS_USERNAME = 'REYNOLDS_USERNAME';
    case REYNOLDS_PASSWORD = 'REYNOLDS_PASSWORD';
    case REYNOLDS_ENDPOINT = 'REYNOLDS_ENDPOINT';
    case REYNOLDS_SENDER_NAME = 'REYNOLDS_SENDER_NAME';
    case REYNOLDS_DEALER_NUMBER = 'REYNOLDS_DEALER_NUMBER';
    case REYNOLDS_STORE_NUMBER = 'REYNOLDS_STORE_NUMBER';
    case REYNOLDS_AREA_NUMBER = 'REYNOLDS_AREA_NUMBER';
    case REYNOLDS_BUSINESS_UNIT_NAME = 'REYNOLDS_BUSINESS_UNIT_NAME';
    case REYNOLDS_DEV_MODE = 'REYNOLDS_DEV_MODE';
}
