<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Reynolds\Enums;

enum CustomFieldEnum: string
{
    case PROSPECT_ID = 'REYNOLDS_PROSPECT_ID';
    case NAME_REC_ID = 'REYNOLDS_NAME_REC_ID';
    case PROSPECT_TYPE = 'REYNOLDS_PROSPECT_TYPE';
    case PROSPECT_STATUS = 'REYNOLDS_PROSPECT_STATUS';
    case PROSPECT_STATUS_TYPE = 'REYNOLDS_PROSPECT_STATUS_TYPE';
    case PROSPECT_NOTE = 'REYNOLDS_PROSPECT_NOTE';
    case PROVIDER_NAME = 'REYNOLDS_PROVIDER_NAME';
    case PROVIDER_SERVICE = 'REYNOLDS_PROVIDER_SERVICE';
    case IS_AI_GENERATED = 'REYNOLDS_IS_AI_GENERATED';
    case IS_CI_LEAD = 'REYNOLDS_IS_CI_LEAD';

    case VEHICLE_OF_INTEREST = 'REYNOLDS_VEHICLE_OF_INTEREST';
    case TRADE_IN = 'REYNOLDS_TRADE_IN';

    case CONSENT_EMAIL = 'REYNOLDS_CONSENT_EMAIL';
    case CONSENT_TEXT = 'REYNOLDS_CONSENT_TEXT';
    case CONSENT_PHONE = 'REYNOLDS_CONSENT_PHONE';
    case CONSENT_MAIL = 'REYNOLDS_CONSENT_MAIL';
    case CONSENT_OPT_OUT = 'REYNOLDS_CONSENT_OPT_OUT';
    case CONSENT_OPT_OUT_USE = 'REYNOLDS_CONSENT_OPT_OUT_USE';
    case SEND_TEXTS_TO = 'REYNOLDS_SEND_TEXTS_TO';

    case PREFERRED_CONTACT = 'REYNOLDS_PREFERRED_CONTACT';
    case LANGUAGE = 'REYNOLDS_LANGUAGE';
    case CONTACT_TYPE = 'REYNOLDS_CONTACT_TYPE';
}
