<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Zoho\Enums;

enum CustomFieldEnum: string
{
    case CLIENT_ID = 'ZOHO_CLIENT_ID';
    case CLIENT_SECRET = 'ZOHO_CLIENT_SECRET';
    case REFRESH_TOKEN = 'ZOHO_REFRESH_TOKEN';
    case ZOHO_LEAD_ID = 'ZOHO_LEAD_ID';
    case DEFAULT_OWNER = 'ZOHO_DEFAULT_OWNER';
    case ZOHO_DEFAULT_LEAD_SOURCE = 'ZOHO_DEFAULT_LEAD_SOURCE';
    case ZOHO_USE_AGENT_NAME = 'ZOHO_USE_AGENT_NAME';
    case FIELDS_MAP = 'ZOHO_FIELDS_MAP';
    case ZOHO_MEMBER_FIELD = 'ZOHO_MEMBER_FIELD';
    case ZOHO_USER_OWNER_ID = 'ZOHO_USER_OWNER_ID';
    case ZOHO_USER_OWNER_MEMBER_NUMBER = 'ZOHO_USER_OWNER_MEMBER_NUMBER';
    case ZOHO_STATUS_NAME = 'ZOHO_STATUS_NAME';
    case ZOHO_HAS_AGENTS_MODULE = 'ZOHO_HAS_AGENTS_MODULE';
    case ZOHO_AGENT_MODULE = 'ZOHO_AGENT_MODULE';
    case ZOHO_LEAD_SYNC_FILES = 'ZOHO_LEAD_SYNC_FILES';
    case ZOHO_DEFAULT_LANDING_PAGE = 'ZOHO_DEFAULT_LANDING_PAGE';
}
