<?php

declare(strict_types=1);

namespace Kanvas\Connectors\LicensePlateExtractor\Enums;

enum CustomFieldEnum: string
{
    case PLATE_NUMBER = 'LICENSE_PLATE_NUMBER';
    case PLATE_REGION = 'LICENSE_PLATE_REGION';
    case PLATE_CONFIDENCE = 'LICENSE_PLATE_CONFIDENCE';
    case VEHICLE_MAKE = 'LICENSE_PLATE_VEHICLE_MAKE';
    case VEHICLE_MODEL = 'LICENSE_PLATE_VEHICLE_MODEL';
    case VEHICLE_COLOR = 'LICENSE_PLATE_VEHICLE_COLOR';
    case VEHICLE_TYPE = 'LICENSE_PLATE_VEHICLE_TYPE';
    case EXTRACTION_PROVIDER = 'LICENSE_PLATE_EXTRACTION_PROVIDER';
    case EXTRACTION_STATUS = 'LICENSE_PLATE_EXTRACTION_STATUS';
    case RAW_RESPONSE = 'LICENSE_PLATE_RAW_RESPONSE';
}
