type WalletResult {
    balance: Money
    message: Mixed
    data: Mixed
}

type WalletTransaction {
    id: ID!
    uuid: String!
    type: String!
    amount: Money! @method(name: "getAmountFloatAttribute")
    confirmed: Boolean!
    status: String
    meta: Mixed
    created_at: DateTimeTz
}

extend type Query @guard {
    getWalletBalance(tag: String!): WalletResult
        @field(
            resolver: "App\\GraphQL\\Souk\\Queries\\Payments\\WalletManagementQuery@getBalance"
        )
    getUserWallet(tag: String!, userId: ID, metadata: Mixed): WalletResult
        @field(
            resolver: "App\\GraphQL\\Souk\\Queries\\Payments\\WalletManagementQuery@getUserWalletBalance"
        )
    getWalletTransactions(
        tag: String!
        where: _
            @whereConditions(
                columns: ["id", "uuid", "type", "amount", "confirmed", "status"]
            )
        orderBy: _ @orderBy(columns: ["id", "status", "created_at"])
    ): [WalletTransaction!]!
        @paginate(
            builder: "App\\GraphQL\\Souk\\Queries\\Payments\\WalletManagementQuery@getTransactions"
            defaultCount: 25
        )
    getUserWalletTransactions(
        tag: String!
        where: _
            @whereConditions(
                columns: ["id", "uuid", "type", "amount", "confirmed", "status"]
            )
        orderBy: _ @orderBy(columns: ["id", "status", "created_at"])
    ): [WalletTransaction!]!
        @paginate(
            builder: "App\\GraphQL\\Souk\\Queries\\Payments\\WalletManagementQuery@getUserTransactions"
            defaultCount: 25
        )
}

extend type Mutation @guardByAppKey {
    flushUserWallet(user_id: ID!, tag: String): WalletResult!
        @field(
            resolver: "App\\GraphQL\\Souk\\Mutations\\Payments\\WalletManagementMutation@flushUserWallet"
        )
    flushCompanyWallet(company_id: ID!, tag: String): WalletResult!
        @field(
            resolver: "App\\GraphQL\\Souk\\Mutations\\Payments\\WalletManagementMutation@flushCompanyWallet"
        )
}
