<?php

declare(strict_types=1);

namespace Kanvas\Connectors\UniversalAssistance\Enums;

enum ConfigurationEnum: string
{
    case BASE_URL = 'UNIVERSAL_ASSISTANCE_API_BASE_URL';
    case USERNAME = 'UNIVERSAL_ASSISTANCE_USERNAME';
    case PASSWORD = 'UNIVERSAL_ASSISTANCE_PASSWORD';
    case ORGANIZATION = 'UNIVERSAL_ASSISTANCE_ORGANIZATION';
    case WSDL_QUOTE = 'UNIVERSAL_ASSISTANCE_WSDL_QUOTE';
    case WSDL_VOUCHER = 'UNIVERSAL_ASSISTANCE_WSDL_VOUCHER';
    case WSDL_QUERY = 'UNIVERSAL_ASSISTANCE_WSDL_QUERY';
    case CONVENIO_INCLUSION_I = 'UNIVERSAL_ASSISTANCE_CONVENIO_INCLUSION_I';
    case CONVENIO_CROSS_SELLING_I = 'UNIVERSAL_ASSISTANCE_CONVENIO_CROSS_SELLING_I';
    case CONVENIO_INCLUSION_II = 'UNIVERSAL_ASSISTANCE_CONVENIO_INCLUSION_II';
    case CONVENIO_CROSS_SELLING_II = 'UNIVERSAL_ASSISTANCE_CONVENIO_CROSS_SELLING_II';
    case CONVENIO_STAND_ALONE = 'UNIVERSAL_ASSISTANCE_CONVENIO_STAND_ALONE';
}
