type LeadStatus {
    id: ID!
    name: String!
    is_default: Int!
}

input LeadStatusInput {
    name: String!
    is_default: Int!
}

extend type Query @guard {
    leadStatuses(
        where: _ @whereConditions(columns: ["name", "is_default", "companies_id"])
        orderBy: _ @orderBy(columns: ["id", "name", "is_default", "created_at"])
    ): [LeadStatus!]!
        @paginate(
            model: "Kanvas\\Guild\\Leads\\Models\\LeadStatus"
            scopes: ["fromPublicOrCurrentApp", "fromCompanyAndGlobal", "notDeleted"]
            defaultCount: 25
        )
}

extend type Mutation @guard {
    createLeadStatus(input: LeadStatusInput!): LeadStatus
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Leads\\LeadStatusManagementMutation@create"
        )
    updateLeadStatus(id: ID!, input: LeadStatusInput!): LeadStatus
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Leads\\LeadStatusManagementMutation@update"
        )
    deleteLeadStatus(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Leads\\LeadStatusManagementMutation@delete"
        )
}
