type Organization {
    id: ID!
    uuid: String!
    company: Company! @belongsTo(relation: "company")
    user: User! @belongsTo(relation: "user")
    name: String!
    address: String
    total_employees: Int!
    created_at: DateTime!
    updated_at: DateTime
    photo: Filesystem @method(name: "getPhoto")
    tags: [Tag!]
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Social\\Queries\\Tags\\TagsQueries@getTagsBuilder"
        )
    files: [Filesystem!]!
        @cacheRedis
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Ecosystem\\Queries\\Filesystem\\FilesystemQuery@getFileByGraphType"
        )
}

input OrganizationInput {
    name: String!
    email: String
    address: String
    city: String
    state: String
    zip: String
}

input OrganizationPeopleInput {
    organization_id: ID!
    peoples_id: [ID!]
}

extend type Mutation @guard {
    createOrganization(input: OrganizationInput!): Organization
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\OrganizationManagementMutation@create"
        )
    updateOrganization(id: ID!, input: OrganizationInput!): Organization
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\OrganizationManagementMutation@update"
        )
    deleteOrganization(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\OrganizationManagementMutation@delete"
        )
    restoreOrganization(id: ID!): Boolean
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\OrganizationManagementMutation@restore"
        )
    addPeopleToOrganization(input: OrganizationPeopleInput!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\PeopleOrganizationMutation@add"
        )
    removePeopleFromOrganization(input: OrganizationPeopleInput!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Guild\\Mutations\\Organizations\\PeopleOrganizationMutation@remove"
        )
}

extend type Query @guard {
    organizations(
        search: String @search
        where: _
            @whereConditions(columns: ["id", "name", "uuid", "total_employees"])
        orderBy: _
            @orderBy(
                columns: [
                    "id"
                    "created_at"
                    "updated_at"
                    "name"
                    "total_employees"
                ]
            )
    ): [Organization!]!
        @paginate(
            model: "Kanvas\\Guild\\Organizations\\Models\\Organization"
            scopes: ["fromCompany", "fromApp", "notDeleted"]
            defaultCount: 25
        )
}
