enum MechanicFilterEnum {
    NOTIFIED
    ASSIGNED
}

type RoadsideAssistanceMetrics {
    period: Period!
    totalCases: Int!
    resolvedCases: Int!
    unresolvedCompletedCases: Int!
    cancelledCases: Int!
    avgResolutionSeconds: Float
    avgResolutionHours: Float
    avgResponseSeconds: Float
    avgResponseHours: Float
}

input RoadsideAssistanceMetricsInput {
    startDate: String
    endDate: String
    provider_company_id: ID
    company_id: ID
}

enum MechanicAvailabilityEnum {
    ACTIVO
    NO_DISPONIBLE
}

enum MechanicWhereColumn {
    ID @enum(value: "users.id")
    FIRSTNAME @enum(value: "users.firstname")
    LASTNAME @enum(value: "users.lastname")
    EMAIL @enum(value: "users.email")
    CREATED_AT @enum(value: "users.created_at")
}

extend type Query @guard {
    mechanics(
        company_id: ID
        availability: MechanicAvailabilityEnum
        where: _
            @whereConditions(columnsEnum: MechanicWhereColumn)
        orderBy: _
            @orderBy(columns: ["id", "firstname", "lastname", "created_at"])
    ): [User!]!
        @paginate(
            builder: "App\\GraphQL\\Connector\\Movipass\\Builders\\MechanicsBuilder@build"
            defaultCount: 25
        )

    roadsideAssistanceMetrics(input: RoadsideAssistanceMetricsInput): RoadsideAssistanceMetrics!
        @field(
            resolver: "App\\GraphQL\\Connector\\Movipass\\Queries\\RoadsideAssistanceMetricsQuery@get"
        )

    mechanicOrders(
        all: Boolean
        mechanic_id: ID
        mechanic_filter: MechanicFilterEnum
        provider_id: ID
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "users_id"
                    "created_at"
                    "updated_at"
                    "fulfillment_status"
                ]
            )
        orderStatus: _
            @whereConditions(
                columns: ["name", "slug", "order_type_id", "id"]
                handler: "App\\GraphQL\\Souk\\Handlers\\OrderStatusHandler"
            )
        orderBy: _
            @orderBy(columns: ["id", "created_at", "updated_at"])
    ): [Order!]!
        @paginate(
            builder: "App\\GraphQL\\Connector\\Movipass\\Builders\\MechanicOrdersBuilder@build"
            defaultCount: 25
        )
}
