<?php

declare(strict_types=1);

namespace Kanvas\Connectors\QuickBooks\Enums;

enum ConfigurationEnum: string
{
    case QUICKBOOKS_CLIENT_ID = 'QUICKBOOKS_CLIENT_ID';
    case QUICKBOOKS_CLIENT_SECRET = 'QUICKBOOKS_CLIENT_SECRET';
    case QUICKBOOKS_ACCESS_TOKEN = 'QUICKBOOKS_ACCESS_TOKEN';
    case QUICKBOOKS_REFRESH_TOKEN = 'QUICKBOOKS_REFRESH_TOKEN';
    case QUICKBOOKS_REALM_ID = 'QUICKBOOKS_REALM_ID';
    case QUICKBOOKS_BASE_URL = 'QUICKBOOKS_BASE_URL';

    // Chart of Accounts Configuration
    case QUICKBOOKS_INCOME_ACCOUNT_ID = 'QUICKBOOKS_INCOME_ACCOUNT_ID';
    case QUICKBOOKS_INVENTORY_ASSET_ACCOUNT_ID = 'QUICKBOOKS_INVENTORY_ASSET_ACCOUNT_ID';
    case QUICKBOOKS_COGS_ACCOUNT_ID = 'QUICKBOOKS_COGS_ACCOUNT_ID';
    case QUICKBOOKS_SHIPPING_INCOME_ACCOUNT_ID = 'QUICKBOOKS_SHIPPING_INCOME_ACCOUNT_ID';
    case QUICKBOOKS_DISCOUNT_ACCOUNT_ID = 'QUICKBOOKS_DISCOUNT_ACCOUNT_ID';

    // Tax Configuration
    case QUICKBOOKS_TAXABLE_CODE = 'QUICKBOOKS_TAXABLE_CODE';
    case QUICKBOOKS_NON_TAXABLE_CODE = 'QUICKBOOKS_NON_TAXABLE_CODE';

    // Additional Settings
    case QUICKBOOKS_AUTO_CREATE_INVOICES = 'QUICKBOOKS_AUTO_CREATE_INVOICES';
    case QUICKBOOKS_INVOICE_PREFIX = 'QUICKBOOKS_INVOICE_PREFIX';
    case QUICKBOOKS_DEFAULT_TERMS = 'QUICKBOOKS_DEFAULT_TERMS';

    case QUICKBOOKS_DEFAULT_ITEM_TYPE = 'quickbooks_default_item_type';

    // New deposit-related configurations
    case QUICKBOOKS_CUSTOMER_DEPOSITS_ACCOUNT_ID = 'quickbooks_customer_deposits_account_id';
    case QUICKBOOKS_DEPOSIT_APPLICATION_ITEM_ID = 'quickbooks_deposit_application_item_id';
    case QUICKBOOKS_UNEARNED_REVENUE_ACCOUNT_ID = 'quickbooks_unearned_revenue_account_id';
    case QUICKBOOKS_UNDEPOSITED_FUNDS_ACCOUNT_ID = 'quickbooks_undeposited_funds_account_id';
}
