<?php

declare(strict_types=1);

namespace Tests\GraphQL\Souk;

use Kanvas\Souk\Wallet\Actions\BuildWalletTransactionMetaAction;
use Kanvas\Souk\Wallet\Enums\TransactionSourceEnum;
use Tests\TestCase;

class WalletAuditTest extends TestCase
{
    public function testBuildMetaProducesCanonicalShape(): void
    {
        $meta = new BuildWalletTransactionMetaAction(
            source: TransactionSourceEnum::RECHARGE_MANUAL,
            actorUserId: 42,
            externalReference: 'order-uuid-123',
            reason: 'Corporate top-up',
        )->execute();

        $this->assertArrayHasKey('source', $meta);
        $this->assertArrayHasKey('idempotency_key', $meta);
        $this->assertArrayHasKey('actor_user_id', $meta);
        $this->assertArrayHasKey('external_reference', $meta);
        $this->assertArrayHasKey('reason', $meta);

        $this->assertEquals('recharge_manual', $meta['source']);
        $this->assertEquals(42, $meta['actor_user_id']);
        $this->assertEquals('order-uuid-123', $meta['external_reference']);
        $this->assertEquals('Corporate top-up', $meta['reason']);
        $this->assertNotNull($meta['idempotency_key']);
    }

    public function testAutoGeneratedIdempotencyKeyIsDeterministic(): void
    {
        $params = [
            'source' => TransactionSourceEnum::PAYMENT,
            'actorUserId' => 7,
            'externalReference' => 'ref-abc',
        ];

        $key1 = new BuildWalletTransactionMetaAction(...$params)->execute()['idempotency_key'];
        $key2 = new BuildWalletTransactionMetaAction(...$params)->execute()['idempotency_key'];

        $this->assertEquals($key1, $key2);
        $this->assertNotEmpty($key1);
    }

    public function testExplicitIdempotencyKeyOverridesAutoHash(): void
    {
        $meta = new BuildWalletTransactionMetaAction(
            source: TransactionSourceEnum::REFUND_TECHNICAL,
            idempotencyKey: 'explicit-key-xyz',
            actorUserId: 1,
            externalReference: 'order-999',
        )->execute();

        $this->assertEquals('explicit-key-xyz', $meta['idempotency_key']);
    }

    public function testNullSourceAndReferenceYieldsNullIdempotencyKey(): void
    {
        $meta = new BuildWalletTransactionMetaAction(
            source: null,
            externalReference: null,
            actorUserId: 1,
        )->execute();

        $this->assertNull($meta['idempotency_key']);
    }

    public function testAdditionalFieldsMergeIntoMeta(): void
    {
        $meta = new BuildWalletTransactionMetaAction(
            source: TransactionSourceEnum::RECHARGE_MANUAL,
            actorUserId: 5,
            externalReference: 'order-ref',
            additional: ['order_id' => 123, 'wallet_type' => 'default'],
        )->execute();

        $this->assertArrayHasKey('order_id', $meta);
        $this->assertArrayHasKey('wallet_type', $meta);
        $this->assertEquals(123, $meta['order_id']);
    }
}
