<?php

declare(strict_types=1);

namespace Kanvas\Intelligence\Agents\Neuron\Tools\Social;

use Kanvas\Apps\Models\Apps;
use Kanvas\Companies\Models\Companies;
use Kanvas\Intelligence\Agents\Attributes\AgentTool;
use Kanvas\Social\Messages\Actions\CreateMessageAction;
use Kanvas\Social\Messages\DataTransferObject\MessageInput;
use Kanvas\Social\Messages\Models\Message;
use Kanvas\Social\MessagesTypes\Services\MessageTypeService;
use Kanvas\Users\Models\Users;
use NeuronAI\Tools\PropertyType;
use NeuronAI\Tools\Tool;
use NeuronAI\Tools\ToolProperty;
use Override;
use Throwable;

#[AgentTool(name: 'Create Message', category: 'social')]
class CreateMessageTool extends Tool
{
    public function __construct(
        private readonly Apps $app,
        private readonly Companies $company,
        private readonly Users $user,
    ) {
        parent::__construct(
            name: 'create_message',
            description: 'Persist a generated Social message without posting it to a channel or sending it externally. '
                . 'Returns the message_id needed by add_message_to_channel.',
        );
    }

    #[Override]
    protected function properties(): array
    {
        return [
            new ToolProperty(
                name: 'content',
                type: PropertyType::STRING,
                description: 'Complete message content generated by the agent or sub-agent.',
                required: true,
            ),
            new ToolProperty(
                name: 'verb',
                type: PropertyType::STRING,
                description: 'Optional message type verb. Defaults to agent-message.',
                required: false,
            ),
            new ToolProperty(
                name: 'parent_message_id',
                type: PropertyType::INTEGER,
                description: 'Optional parent message ID when creating a reply.',
                required: false,
            ),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function __invoke(
        string $content,
        ?string $verb = null,
        ?int $parent_message_id = null,
    ): array {
        $content = trim($content);
        $verb = trim((string) $verb);

        if ($content === '') {
            return [
                'status' => 'error',
                'message' => 'The message content is empty.',
            ];
        }

        $parent = null;
        if ($parent_message_id !== null) {
            $parent = $this->findMessage($parent_message_id);
            if ($parent === null) {
                return [
                    'status' => 'error',
                    'message' => 'The parent message does not exist in the current app and company.',
                ];
            }
        }

        try {
            $messageType = MessageTypeService::getOrCreate(
                app: $this->app,
                verb: $verb === '' ? 'agent-message' : $verb,
            );
            $action = new CreateMessageAction(new MessageInput(
                app: $this->app,
                company: $this->company,
                user: $this->user,
                type: $messageType,
                message: ['content' => $content],
                parent_id: $parent?->getId(),
                parent_unique_id: $parent?->uuid,
            ));
            $action->runWorkflow = false;
            $message = $action->execute();
        } catch (Throwable $e) {
            report($e);

            return [
                'status' => 'error',
                'message' => 'The message could not be created.',
            ];
        }

        return [
            'status' => 'success',
            'message_id' => $message->getId(),
            'message_uuid' => $message->uuid,
            'content' => $content,
        ];
    }

    private function findMessage(int $messageId): ?Message
    {
        return Message::query()
            ->whereKey($messageId)
            ->where('apps_id', $this->app->getId())
            ->where('companies_id', $this->company->getId())
            ->where('is_deleted', 0)
            ->first();
    }
}
