<?php

declare(strict_types=1);

namespace Kanvas\Intelligence\Agents\Neuron\Tools\Social;

use Baka\Http\Exceptions\SsrfException;
use Baka\Http\SafeUrl;
use Kanvas\Apps\Models\Apps;
use Kanvas\Companies\Models\Companies;
use Kanvas\Filesystem\Enums\AllowedFileExtensionEnum;
use Kanvas\Intelligence\Agents\Attributes\AgentTool;
use Kanvas\Social\Messages\Actions\CreateMessageAction;
use Kanvas\Social\Messages\DataTransferObject\MessageInput;
use Kanvas\Social\Messages\Models\Message;
use Kanvas\Social\MessagesTypes\Services\MessageTypeService;
use Kanvas\Users\Models\Users;
use NeuronAI\Tools\ArrayProperty;
use NeuronAI\Tools\PropertyType;
use NeuronAI\Tools\Tool;
use NeuronAI\Tools\ToolProperty;
use Override;
use Throwable;

#[AgentTool(name: 'Create Message', category: 'social')]
class CreateMessageTool extends Tool
{
    public function __construct(
        private readonly Apps $app,
        private readonly Companies $company,
        private readonly Users $user,
    ) {
        parent::__construct(
            name: 'create_message',
            description: 'Persist a generated Social message without posting it to a channel or sending it externally. '
                . 'The body can be plain text or a JSON object of named fields, and photos or documents can be '
                . 'attached by public URL. Set trigger_automation when the message is work product the company\'s '
                . 'workflows should act on — publishing or filing it — rather than plain conversation. '
                . 'Returns the message_id needed by add_message_to_channel.',
        );
    }

    #[Override]
    protected function properties(): array
    {
        return [
            new ToolProperty(
                name: 'content',
                type: PropertyType::STRING,
                description: 'Complete message content generated by the agent or sub-agent. Pass plain text for '
                    . 'a normal message, or a JSON object when the message has named fields — '
                    . '{"title": "...", "body": "...", "url": "..."} — and those fields are stored as the '
                    . 'message itself, not nested under "content".',
                required: true,
            ),
            new ToolProperty(
                name: 'verb',
                type: PropertyType::STRING,
                description: 'Optional message type verb. Defaults to agent-message.',
                required: false,
            ),
            new ToolProperty(
                name: 'parent_message_id',
                type: PropertyType::INTEGER,
                description: 'Optional parent message ID when creating a reply.',
                required: false,
            ),
            new ToolProperty(
                name: 'trigger_automation',
                type: PropertyType::BOOLEAN,
                description: 'Default false. Set true when this message is work product the company\'s '
                    . 'workflows should pick up — an article to publish, a report to file. The verb must then '
                    . 'name a message type that ALREADY exists, because a rule is watching that exact type; '
                    . 'the call fails and lists the real types rather than inventing one. Leave false for '
                    . 'plain conversation, which must not set anything running.',
                required: false,
            ),
            new ArrayProperty(
                name: 'file_urls',
                description: 'Optional list of public http(s) URLs to attach to the message — photos, images '
                    . 'or documents. The URL is stored as-is, so it must already be publicly reachable and '
                    . 'end in a file extension (.jpg, .png, .pdf, ...). Never invent a URL.',
                required: false,
                items: new ToolProperty(
                    name: 'file_url',
                    type: PropertyType::STRING,
                    description: 'A public http(s) URL of the file to attach.',
                ),
            ),
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function __invoke(
        string $content,
        ?string $verb = null,
        ?int $parent_message_id = null,
        ?array $file_urls = null,
        ?bool $trigger_automation = null,
    ): array {
        $triggerAutomation = (bool) $trigger_automation;
        $content = trim($content);
        $verb = trim((string) $verb);

        if ($content === '') {
            return [
                'status' => 'error',
                'message' => 'The message content is empty.',
            ];
        }

        $messageBody = $this->resolveMessageBody($content);

        $fileUrls = $this->normalizeUrls($file_urls ?? []);
        $rejectedUrls = array_values(array_filter($fileUrls, fn (string $url): bool => ! $this->isAttachableUrl($url)));

        if ($rejectedUrls !== []) {
            return [
                'status' => 'error',
                'message' => 'These URLs cannot be attached: they must be public http(s) links ending in a '
                    . 'supported file extension. Drop them or fix them, then call create_message again.',
                'rejected_urls' => $rejectedUrls,
            ];
        }

        $parent = null;
        if ($parent_message_id !== null) {
            $parent = $this->findMessage($parent_message_id);
            if ($parent === null) {
                return [
                    'status' => 'error',
                    'message' => 'The parent message does not exist in the current app and company.',
                ];
            }
        }

        try {
            $messageType = MessageTypeService::getOrCreate(
                app: $this->app,
                verb: $verb === '' ? 'agent-message' : $verb,
            );
            $action = new CreateMessageAction(new MessageInput(
                app: $this->app,
                company: $this->company,
                user: $this->user,
                type: $messageType,
                message: $messageBody,
                parent_id: $parent?->getId(),
                parent_unique_id: $parent?->uuid,
            ));
            $action->runWorkflow = false;
            $message = $action->execute();
        } catch (Throwable $e) {
            report($e);

            return [
                'status' => 'error',
                'message' => 'The message could not be created.',
            ];
        }

        $result = [
            'status' => 'success',
            'message_id' => $message->getId(),
            'message_uuid' => $message->uuid,
            'message' => $messageBody,
        ];

        if ($fileUrls === []) {
            return $result;
        }

        // The message is already committed, so a failed attach must not read as a failed create —
        // the model would create the whole message a second time.
        try {
            $message->addMultipleFilesFromUrl(array_map(
                fn (string $url): array => ['url' => $url, 'name' => $this->fileNameFromUrl($url)],
                $fileUrls,
            ));

            $result['files_attached'] = $fileUrls;
        } catch (Throwable $e) {
            report($e);

            $result['files_attached'] = [];
            $result['note'] = 'The message was saved but the files could not be attached. Do not create the '
                . 'message again — say the attachments failed.';
        }

        return $result;
    }

    /**
     * A JSON object is stored as the message itself so downstream readers get named fields; anything
     * else (plain text, a JSON list, a bare scalar) keeps the `content` wrapper it has always had.
     *
     * @return array<string, mixed>
     */
    private function resolveMessageBody(string $content): array
    {
        $decoded = json_decode($content, true);

        if (is_array($decoded) && $decoded !== [] && ! array_is_list($decoded)) {
            return $decoded;
        }

        return ['content' => $content];
    }

    /**
     * @return list<string>
     */
    private function normalizeUrls(array $urls): array
    {
        $normalized = [];

        foreach ($urls as $url) {
            if (! is_string($url) || trim($url) === '') {
                continue;
            }

            $normalized[] = trim($url);
        }

        return array_values(array_unique($normalized));
    }

    /**
     * The URL is stored as a reference rather than downloaded, so the SSRF check guards whoever fetches
     * it later — a publisher, an optimizer, a client — from an LLM-supplied link to an internal host.
     */
    private function isAttachableUrl(string $url): bool
    {
        $path = (string) parse_url($url, PHP_URL_PATH);
        $extension = strtolower(pathinfo($path, PATHINFO_EXTENSION));

        if (! in_array($extension, AllowedFileExtensionEnum::WORK_FILES->getAllowedExtensions(), true)) {
            return false;
        }

        try {
            SafeUrl::assertSafe($url);
        } catch (SsrfException) {
            return false;
        }

        return true;
    }

    private function fileNameFromUrl(string $url): string
    {
        $name = basename((string) parse_url($url, PHP_URL_PATH));

        return $name === '' ? 'attachment' : $name;
    }

    private function findMessage(int $messageId): ?Message
    {
        return Message::query()
            ->whereKey($messageId)
            ->where('apps_id', $this->app->getId())
            ->where('companies_id', $this->company->getId())
            ->where('is_deleted', 0)
            ->first();
    }
}
