<?php

declare(strict_types=1);

namespace Kanvas\Connectors\Intellicheck\Jobs;

use Illuminate\Http\Request;
use Kanvas\Guild\Leads\Models\Lead;
use Kanvas\Guild\Leads\Models\LeadReceiver;
use Kanvas\Workflow\Attributes\WorkflowAction;
use Kanvas\Workflow\Enums\IntegrationsEnum;
use Kanvas\Workflow\Enums\WorkflowEnum;
use Kanvas\Workflow\Jobs\ProcessWebhookJob;
use Kanvas\Workflow\Models\ReceiverWebhook;
use Override;
use Throwable;

/**
 * The bot's callback URL is generated by us, so the query string keeps the legacy `token` / `lead` /
 * `eid` shape. Only the Intellicheck-specific parse lives here; scoring is the shared
 * `generate-id-verification` path.
 */
#[WorkflowAction(
    name: 'Intellicheck ID Verification Receiver',
    description: 'Receives the Intellicheck scan result (base64 body), unwraps it and fires '
        . 'generate-id-verification against the engagement the scan belongs to.',
    integration: IntegrationsEnum::INTELLICHECK,
    params: [
        'token' => 'Uuid of the LeadReceiver the ID-verification engagement was created under.',
        'lead' => 'Uuid of the lead being verified.',
        'eid' => 'Id or uuid of the ID-verification engagement the scan belongs to.',
    ],
    requiredParams: ['token', 'lead', 'eid'],
)]
final class IdVerificationReceiverJob extends ProcessWebhookJob
{
    /**
     * Rejected here because a 200 carrying an error string is indistinguishable from success to the bot.
     */
    #[Override]
    public static function authenticateRequest(Request $request, ReceiverWebhook $receiver): bool
    {
        return (string) $request->input('token', '') !== ''
            && (string) $request->input('lead', '') !== ''
            && (string) $request->input('eid', '') !== '';
    }

    #[Override]
    public function execute(): array
    {
        // A replay through RetryWebhookCallAction dispatches this job without re-running
        // authenticateRequest(), so the three params cannot be assumed present.
        $payload = $this->webhookRequest->payload ?? [];
        $token = (string) ($payload['token'] ?? '');
        $leadUuid = (string) ($payload['lead'] ?? '');
        $engagementId = $payload['eid'] ?? null;
        $app = $this->receiver->app;

        if ($token === '' || $leadUuid === '' || $engagementId === null || $engagementId === '') {
            return ['result' => false, 'message' => 'Missing token, lead or eid'];
        }

        $verificationData = $this->decodeBody();

        if ($verificationData === []) {
            return [
                'result' => false,
                'message' => 'Body is not base64-encoded JSON, or carried no verification result',
            ];
        }

        $leadReceiver = LeadReceiver::where('uuid', $token)
            ->fromApp($app)
            ->notDeleted()
            ->first();

        if ($leadReceiver === null) {
            return ['result' => false, 'message' => 'Invalid token'];
        }

        try {
            $lead = Lead::getByUuid($leadUuid, $app);
        } catch (Throwable) {
            return ['result' => false, 'message' => 'Invalid lead'];
        }

        if ((int) $lead->companies_id !== (int) $leadReceiver->companies_id) {
            return ['result' => false, 'message' => 'Invalid company'];
        }

        // The selfie must never be persisted inside the message payload, so it travels separately.
        $faceImage = $verificationData['facial']['data']['photoFace'] ?? null;
        unset($verificationData['facial']['data']['photoFace']);

        // No `company` param: the rules are scoped by the lead's own company, which can differ from the
        // webhook's.
        $lead->fireWorkflow(
            WorkflowEnum::GENERATE_ID_VERIFICATION->value,
            params: [
                'app' => $app,
                'eid' => $engagementId,
                'intellicheck' => $verificationData,
                'images' => ['face' => $faceImage],
            ]
        );

        return [
            'result' => true,
            'message' => 'Success Intellicheck Receiver',
            'lead_id' => $lead->getId(),
            'engagement' => $engagementId,
        ];
    }

    /**
     * The bot posts base64(JSON) as the raw body, and the payload we score sits under
     * `private_data.result` — the legacy controller unwrapped it before forwarding, which is the shape
     * `IdVerificationService` was written against.
     */
    private function decodeBody(): array
    {
        $raw = (string) ($this->webhookRequest->raw_payload ?? '');

        if ($raw === '') {
            return [];
        }

        $decoded = json_decode((string) base64_decode($raw, true), true);

        if (! is_array($decoded)) {
            return [];
        }

        $result = $decoded['private_data']['result'] ?? $decoded;

        return is_array($result) ? $result : [];
    }
}
