type WorkflowReceiversHistory {
    id: ID!
    uuid: String!
    receiver: WorkflowReceiver @belongsTo(relation: "receiverWebhook")
    status: String
    url: String
    headers: Mixed
    payload: Mixed
    results: Mixed
    exception: Mixed
    created_at: DateTime
}

type WorkflowReceiver {
    id: ID!
    uuid: String!
    name: String!
    description: String
    url: String @method(name: "getUrl")
    is_active: Boolean!
    run_async: Boolean!
    configuration: Mixed
    company: Company
    action: WorkflowAction!
    webhookCalls: [WorkflowReceiversHistory!] @hasMany(relation: "webhookCalls")
    created_at: DateTime
    updated_at: DateTime
}

input ReceiverWebhookInput {
    action_id: Int!
    name: String!
    description: String
    configuration: Mixed
    is_active: Boolean
    run_async: Boolean
}

input UpdateReceiverWebhookInput {
    action_id: Int
    name: String
    description: String
    configuration: Mixed
    is_active: Boolean
    run_async: Boolean
}

enum WorkflowReceiversHistoryEnumColumn {
    ID @enum(value: "receiver_webhook_calls.id")
    NAME @enum(value: "receiver_webhooks.name")
    RECEIVER_STATUS @enum(value: "receiver_webhook_calls.status")
    RECEIVER_ACTION @enum(value: "actions.id")
}

enum WorkflowReceiverStatusEnum {
    PENDING @enum(value: "pending")
    SUCCESS @enum(value: "success")
    FAILED @enum(value: "failed")
}

enum workflowReceiverHistoryEnumColumn {
    ID @enum(value: "receiver_webhook_calls.id")
    NAME @enum(value: "receiver_webhooks.name")
    CREATED_AT @enum(value: "receiver_webhook_calls.created_at")
    STATUS @enum(value: "receiver_webhook_calls.status")
}

extend type Mutation @guardByAdmin {
    createReceiverWebhook(input: ReceiverWebhookInput!): WorkflowReceiver!
        @field(
            resolver: "App\\GraphQL\\Workflow\\Mutations\\Receivers\\ReceiverWebhookMutationManagement@create"
        )
    updateReceiverWebhook(id: ID!, input: UpdateReceiverWebhookInput!): WorkflowReceiver!
        @field(
            resolver: "App\\GraphQL\\Workflow\\Mutations\\Receivers\\ReceiverWebhookMutationManagement@update"
        )
    deleteReceiverWebhook(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Workflow\\Mutations\\Receivers\\ReceiverWebhookMutationManagement@delete"
        )
}

extend type Query @guard {
    receiverWebhooks(
        search: String @search
        where: _ @whereConditions(columns: ["id", "name", "action_id", "is_active"])
        orderBy: _ @orderBy(columns: ["id", "name", "created_at", "updated_at"])
    ): [WorkflowReceiver!]!
        @paginate(
            model: "Kanvas\\Workflow\\Models\\ReceiverWebhook"
            scopes: ["fromApp", "fromCompany", "notDeleted"]
            defaultCount: 25
        )
    workflowReceiverHistory(
        where: _
            @whereConditions(columnsEnum: WorkflowReceiversHistoryEnumColumn)
        hasAction: _
            @whereHasConditions(
                columns: ["id", "name"]
                handler: "App\\GraphQL\\Workflow\\Builders\\Receivers\\ReceiversBuilder@getHasAction"
            )
        orderBy: _ @orderBy(columnsEnum: workflowReceiverHistoryEnumColumn)
    ): [WorkflowReceiversHistory!]!
        @paginate(
            builder: "App\\GraphQL\\Workflow\\Builders\\Receivers\\ReceiversBuilder@getReceiversHistory"
            scopes: ["notDeleted"]
            defaultCount: 25
        )
    receiverStatus: [WorkflowReceiverStatusEnum!]!
        @field(resolver: "App\\GraphQL\\Workflow\\Queries\\ReceiverStatusQuery")
}
