<?php

declare(strict_types=1);

namespace Kanvas\Connectors\DealerSocket\Enums;

enum CustomFieldEnum: string
{
    case DEALER_SOCKET_CREDENTIAL = 'DEALER_SOCKET_CREDENTIAL';
    case DEALER_SOCKET_PUBLIC_KEY = 'DEALER_SOCKET_PUBLIC_KEY';
    case DEALER_SOCKET_PRIVATE_KEY = 'DEALER_SOCKET_PRIVATE_KEY';
    case DEALER_SOCKET_DEALER_ID = 'DEALER_SOCKET_DEALER_ID';
    case DEALER_SOCKET_DEALER_NUMBER = 'DEALER_SOCKET_DEALER_NUMBER';
    case DEALER_SOCKET_USERNAME = 'DEALER_SOCKET_USERNAME';
    case DEALER_SOCKET_PASSWORD = 'DEALER_SOCKET_PASSWORD';
    case DEALER_SOCKET_VENDOR_NAME = 'DEALER_SOCKET_VENDOR_NAME';
    case DEALER_SOCKET_LEAD_ID = 'DEALER_SOCKET_LEAD_ID';
    case DEALER_SOCKET_CUSTOMER_ID = 'DEALER_SOCKET_CUSTOMER_ID';
}
