name: Uninstall Helm Chart
on: workflow_dispatch

jobs:
  Uninstall-Helm-Chart:
    runs-on: ubuntu-latest
    environment: .github/workflows/${GITHUB_REF##*/}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Kubernetes toolset
        uses: stefanprodan/kube-tools@v1.7.2
        with:
          kubectl: 1.23.0

      - name: Uninstall Helm Chart
        run: |
            #configure aws login
            if rm -rf /home/runner/.aws
            then
            echo old credentials removed
            fi

            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_CICD }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD }}
            aws eks update-kubeconfig   --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}
            
            #Uninstall current Helm Chart
            helm uninstall ${{ secrets.INSTANCE_NAME }} helm \
            --namespace ${{ secrets.INSTANCE_NAME }}

    
