extend type User {
    pivot: SocialChannelPivot
}

type SocialChannel {
    id: ID!
    name: String!
    uuid: String
    slug: String
    description: String!
    entity_namespace: String!
    entity_id: ID!
    last_message_id: ID
    title: String
    messages: [Message!]! @belongsToMany
    users: [User!]! @belongsToMany
    systemModule: SystemModule! @belongsTo
    created_at: DateTime!
}

input SocialChannelInput {
    name: String!
    slug: String
    description: String!
    entity_namespace_uuid: String!
    entity_id: ID!
}

enum UsersRolesChannel {
    Admin @enum(value: 1)
    User @enum(value: 2)
}

type SocialChannelPivot {
    roles_id: UsersRolesChannel!
}

input AttachUserInput {
    channel_id: ID!
    user_id: ID!
    roles_id: UsersRolesChannel!
}

enum ChannelColumns {
    ID @enum(value: "channels.id")
    NAME @enum(value: "channels.name")
    SLUG @enum(value: "channels.slug")
    DESCRIPTION @enum(value: "channels.description")
    ENTITY_NAMESPACE @enum(value: "channels.entity_namespace")
    ENTITY_ID @enum(value: "channels.entity_id")
    CREATED_AT @enum(value: "channels.created_at")
    UPDATED_AT @enum(value: "channels.updated_at")
    LAST_MESSAGE_ID @enum(value: "channels.last_message_id")
    TITLE @enum(value: "channels.title")
    UUID @enum(value: "channels.uuid")
}

extend type Query {
    socialChannels(
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "name"
                    "slug"
                    "description"
                    "entity_namespace"
                    "entity_id"
                ]
            )
        orderBy: _ @orderBy(columnsEnum: ChannelColumns)
    ): [SocialChannel!]!
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Social\\Builders\\Channels\\GetSocialChannelsBuilder@getChannels"
            scopes: ["fromApp"]
        )
}

extend type Mutation {
    createSocialChannel(input: SocialChannelInput!): SocialChannel
        @field(
            resolver: "App\\GraphQL\\Social\\Mutations\\Channels\\ChannelsManagementMutation@createChannel"
        )
    updateSocialChannel(id: ID!, input: SocialChannelInput!): SocialChannel
        @field(
            resolver: "App\\GraphQL\\Social\\Mutations\\Channels\\ChannelsManagementMutation@updateChannel"
        )
    deleteSocialChannel(id: ID!): SocialChannel
        @field(
            resolver: "App\\GraphQL\\Social\\Mutations\\Channels\\ChannelsManagementMutation@deleteChannel"
        )
    attachUserToSocialChannel(input: AttachUserInput!): SocialChannel
        @field(
            resolver: "App\\GraphQL\\Social\\Mutations\\Channels\\ChannelsManagementMutation@attachUserToChannel"
        )
    detachUserToSocialChannel(channel_id: ID!, user_id: ID!): SocialChannel
        @field(
            resolver: "App\\GraphQL\\Social\\Mutations\\Channels\\ChannelsManagementMutation@detachUserToChannel"
        )
}
