type Facilitator {
    id: ID!
    uuid: String!
    slug: String!
    people: People! @belongsTo(relation: "people")
    user: User! @belongsTo(relation: "user")
    company: Company! @belongsTo(relation: "company")
    description: String
    identification: String
    resume: String
    photo: Filesystem @method(name: "getPhoto")
    created_at: DateTime
    updated_at: DateTime
    files: [Filesystem!]!
        @cacheRedis
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Ecosystem\\Queries\\Filesystem\\FilesystemQuery@getFileByGraphType"
        )
    custom_fields: [CustomField!]!
        @paginate(
            defaultCount: 25
            resolver: "App\\GraphQL\\Ecosystem\\Queries\\CustomFields\\CustomFieldQuery@getAllByGraphType"
        )
    tags: [Tag!]
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Social\\Queries\\Tags\\TagsQueries@getTagsBuilder"
        )
}

type EventVersionFacilitator {
    id: ID!
    event_version: EventVersion! @belongsTo(relation: "eventVersion")
    facilitator: Facilitator! @belongsTo(relation: "facilitator")
    created_at: DateTime
    updated_at: DateTime
}

input FacilitatorInput {
    people_id: ID!
    identification: String
    resume: String
    description: String
    custom_fields: [CustomFieldEntityInput!]
    tags: [TagInput!]
    files: [FilesystemInputUrl!]
}

input FacilitatorUpdateInput {
    people_id: ID
    identification: String
    resume: String
    description: String
    custom_fields: [CustomFieldEntityInput!]
    tags: [TagInput!]
    files: [FilesystemInputUrl!]
}

input FacilitatorEventVersionInput {
    event_version_id: ID!
    facilitator_id: ID!
}

extend type Mutation @guard {
    createFacilitator(input: FacilitatorInput!): Facilitator!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Facilitators\\FacilitatorMutation@create"
        )
    updateFacilitator(id: ID!, input: FacilitatorUpdateInput!): Facilitator!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Facilitators\\FacilitatorMutation@update"
        )
    deleteFacilitator(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Facilitators\\FacilitatorMutation@delete"
        )
    attachFacilitatorToEventVersion(
        input: FacilitatorEventVersionInput!
    ): EventVersionFacilitator!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Facilitators\\FacilitatorMutation@attachToEventVersion"
        )
    detachFacilitatorFromEventVersion(
        input: FacilitatorEventVersionInput!
    ): Boolean!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Facilitators\\FacilitatorMutation@detachFromEventVersion"
        )
}

extend type Query @guard {
    facilitators(
        search: String @search
        where: _
            @whereConditions(columns: ["id", "uuid", "name", "slug", "companies_id", "people_id"])
        orderBy: _ @orderBy(columns: ["id", "created_at", "updated_at"])
    ): [Facilitator!]!
        @paginate(
            scopes: ["fromApp", "fromCompany", "notDeleted"]
            model: "Kanvas\\Event\\Facilitators\\Models\\Facilitator"
            defaultCount: 25
        )
}