type Participant {
    id: ID!
    uuid: String!
    slug: String!
    people: People! @belongsTo(relation: "people")
    user: User! @belongsTo(relation: "user")
    company: Company! @belongsTo(relation: "company")
    themeArea: EventThemeArea @belongsTo(relation: "themeArea")
    is_prospect: Boolean!
    photo: Filesystem @method(name: "getPhoto")
    created_at: DateTime
    updated_at: DateTime
    files: [Filesystem!]!
        @cacheRedis
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Ecosystem\\Queries\\Filesystem\\FilesystemQuery@getFileByGraphType"
        )
    custom_fields: [CustomField!]!
        @paginate(
            defaultCount: 25
            resolver: "App\\GraphQL\\Ecosystem\\Queries\\CustomFields\\CustomFieldQuery@getAllByGraphType"
        )
    tags: [Tag!]
        @paginate(
            defaultCount: 25
            builder: "App\\GraphQL\\Social\\Queries\\Tags\\TagsQueries@getTagsBuilder"
        )
}

type ParticipantPass {
    id: ID!
    participant: Participant! @belongsTo(relation: "participant")
    event_version: EventVersion! @belongsTo(relation: "eventVersion")
    event: Event! @belongsTo(relation: "event")
    motive: ParticipantPassMotive! @belongsTo(relation: "motive")
    expiration_date: Date!
    used_date: Date
    code: String!
    created_at: DateTime
    updated_at: DateTime
}

type ParticipantType {
    id: ID!
    name: String!
    user: User! @belongsTo(relation: "user")
    created_at: DateTime
    updated_at: DateTime
}

type ParticipantPassMotive {
    id: ID!
    name: String!
    user: User! @belongsTo(relation: "user")
    created_at: DateTime
    updated_at: DateTime
}

input PeopleEventVersionInput {
    people_id: ID!
    event_version_id: ID!
    ticket_price: Money
    discount: Money
    invoice_date: Date
    payment_status: String
    metadata: Mixed
    participant_type_id: ID
    custom_fields: [CustomFieldEntityInput!]
    tags: [TagInput!]
    files: [FilesystemInputUrl!]
}

input CopyParticipantsInput {
    from_event_version_id: ID!
    to_event_version_id: ID!
}

input ParticipantInput {
    people_id: ID!
    theme_area_id: ID
    is_prospect: Boolean
    general_representative: String
    custom_fields: [CustomFieldEntityInput!]
    tags: [TagInput!]
    files: [FilesystemInputUrl!]
}

input ParticipantUpdateInput {
    people_id: ID
    theme_area_id: ID
    is_prospect: Boolean
    general_representative: String
    custom_fields: [CustomFieldEntityInput!]
    tags: [TagInput!]
    files: [FilesystemInputUrl!]
}

extend type Mutation @guard {
    createParticipant(input: ParticipantInput!): Participant!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\ParticipantMutation@create"
        )
    updateParticipant(id: ID!, input: ParticipantUpdateInput!): Participant!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\ParticipantMutation@update"
        )
    deleteParticipant(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\ParticipantMutation@delete"
        )

    addPeopleToEventVersion(input: PeopleEventVersionInput!): Participant!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\EventParticipantManagementMutation@addPeopleToEventVersion"
        )
    removePeopleInEventVersion(input: PeopleEventVersionInput!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\EventParticipantManagementMutation@removePeopleFromEventVersion"
        )
    copyParticipantsToEventVersion(input: CopyParticipantsInput!): Int!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Participants\\EventParticipantManagementMutation@copyParticipantsToEventVersion"
        )

    createParticipantType(input: EventLookupInput!): ParticipantType!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Lookups\\EventLookupMutation@createParticipantType"
        )
    updateParticipantType(
        id: ID!
        input: EventLookupUpdateInput!
    ): ParticipantType!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Lookups\\EventLookupMutation@updateParticipantType"
        )
    deleteParticipantType(id: ID!): Boolean!
        @field(
            resolver: "App\\GraphQL\\Event\\Mutations\\Lookups\\EventLookupMutation@deleteParticipantType"
        )
}

extend type Query @guard {
    participants(
        search: String @search
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "uuid"
                    "name"
                    "slug"
                    "companies_id"
                    "people_id"
                    "is_prospect"
                ]
            )
        orderBy: _ @orderBy(columns: ["id", "created_at", "updated_at"])
    ): [Participant!]!
        @paginate(
            scopes: ["fromApp", "fromCompany", "notDeleted"]
            model: "Kanvas\\Event\\Participants\\Models\\Participant"
            defaultCount: 25
        )
    participantTypes(
        search: String @search
        where: _ @whereConditions(columns: ["id", "name", "companies_id"])
        orderBy: _ @orderBy(columns: ["id", "created_at", "updated_at"])
    ): [ParticipantType!]!
        @paginate(
            scopes: ["fromApp", "fromCompany", "notDeleted"]
            model: "Kanvas\\Event\\Participants\\Models\\ParticipantType"
            defaultCount: 25
        )
    participantPassMotives(
        search: String @search
        where: _ @whereConditions(columns: ["id", "name", "companies_id"])
        orderBy: _ @orderBy(columns: ["id", "created_at", "updated_at"])
    ): [ParticipantPassMotive!]!
        @paginate(
            scopes: ["fromApp", "fromCompany", "notDeleted"]
            model: "Kanvas\\Event\\Participants\\Models\\ParticipantPassMotive"
            defaultCount: 25
        )
}
