type TimeSlots {
    id: ID!
    apps_id: ID!
    companies_id: ID!
    resources_id: ID!
    resources_type: String!
    schedule_rules_id: ID
    start_at: DateTime!
    end_at: DateTime!
    capacity: Int!
    status: String
    price_snapshot: Float
    currency: String
    meta: Mixed
    created_at: DateTime
    updated_at: DateTime
    resource: TimeSlotResource @morphTo
    scheduleRule: ScheduleRules @belongsTo(relation: "scheduleRule")
    is_from_schedule_rule: Boolean! @method(name: "isFromScheduleRule")
    is_standalone: Boolean! @method(name: "isStandalone")
}

union TimeSlotResource = Variant | Product

input TimeSlotsFilterInput {
    resources_id: ID
    resources_type: String
    start_at: DateTime
    end_at: DateTime
    status: String
    date_from: DateTime
    date_to: DateTime
}

extend type Query @guard {
    timeSlots(
        search: String @search
        where: _
            @whereConditions(
                columns: [
                    "id"
                    "companies_id"
                    "resources_id"
                    "resources_type"
                    "schedule_rules_id"
                    "start_at"
                    "end_at"
                    "capacity"
                    "status"
                    "currency"
                ]
            )
        resourceType: _
            @whereConditions(
                columns: ["resources_type"]
                handler: "App\\GraphQL\\Event\\Handlers\\ResourceTypeHandler"
            )
        orderBy: _ @orderBy(columns: ["id", "start_at", "end_at", "created_at", "updated_at"])
    ): [TimeSlots!]!
        @paginate(
            scopes: ["fromApp", "fromCompany"]
            model: "Kanvas\\Event\\Events\\Models\\TimeSlots"
            defaultCount: 25
        )
}